field: 40b5fa5a-5d55-4783-aac4-a7c9cc3c991d # Accommodation Layouts 2
fieldLayouts:
  e0e51b55-3853-4431-984a-7b62c9e83e15:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e3849f1a-fd67-4828-937f-f256bba6987b # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 847ff6c7-d348-41a6-9246-bac604361bde
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ca7b6967-d24c-401a-8e3e-1ac0ca8f2b43 # Headline
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: afd58f75-a8e7-43a1-bbf1-02613562c058
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ef4a4b55-2f0b-4ae9-a241-c51388f63ff5 # Description
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bfad8a2e-6496-4343-b1a9-0cd8238133f1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 75cef8a5-2542-492d-9b62-1e9ff98d84db
        userCondition: null
fields:
  ca7b6967-d24c-401a-8e3e-1ac0ca8f2b43: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e3849f1a-fd67-4828-937f-f256bba6987b: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  ef4a4b55-2f0b-4ae9-a241-c51388f63ff5: # Description
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: null
    name: Description
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      characterLimit: null
      ckeConfig: 4dc3cdd6-aaf2-421a-bd6c-aaa6de96e874 # Default
      columnType: text
      defaultTransform: null
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      showWordCount: false
      sourceEditingGroups: '*'
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: accommodationLayout
name: 'Accommodation Layout'
sortOrder: 1
