field: 0b7b3861-eb22-491a-8a7c-85aa93cbf287 # Accommodations
fieldLayouts:
  3c92c043-9843-4cd9-9ba0-58c319bf5a9b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5948f33e-dfdb-4f6c-bc85-fd56f965bf2c # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26afcfd9-c386-4cd4-a923-9c44ef544f57
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a1753ecd-41fd-41a1-bae9-5ee530faed0b # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 91eaf3fa-76b9-41fc-8059-295be338bc20
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: eba4f40b-54de-43c7-ab5e-c180559134e8 # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e95c28e1-ee04-4779-909b-4bcab554ecdc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1bdac2fc-1795-48df-8744-7e86ce6e811d
        userCondition: null
fields:
  5948f33e-dfdb-4f6c-bc85-fd56f965bf2c: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      restrictedLocationSubpath: null
      selectionLabel: 'Add an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  a1753ecd-41fd-41a1-bae9-5ee530faed0b: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  eba4f40b-54de-43c7-ab5e-c180559134e8: # Button
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: button
    instructions: null
    name: Button
    searchable: true
    settings:
      allowCustomText: true
      allowTarget: false
      defaultText: null
      selectLinkText: ''
      types:
        __assoc__:
          -
            - presseddigital\linkit\models\Email
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Phone
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Url
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
                -
                  - allowAlias
                  - '1'
                -
                  - allowMailto
                  - '1'
                -
                  - allowHash
                  - '1'
                -
                  - allowPaths
                  - '1'
          -
            - presseddigital\linkit\models\Twitter
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Facebook
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Instagram
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\LinkedIn
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Entry
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  -
                    - 'section:0c9fc74f-f5c7-4b5f-8b80-8ea98aa0999e' # Accommodations
                -
                  - customSelectionLabel
                  - ''
          -
            - presseddigital\linkit\models\Category
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - ''
          -
            - presseddigital\linkit\models\Asset
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - ''
          -
            - presseddigital\linkit\models\User
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - ''
                -
                  - userPath
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: presseddigital\linkit\fields\LinkitField
handle: accommodation
name: Accommodation
sortOrder: 1
