field: 86dbf20b-c736-4e15-ad25-8d09e62097d4 # Accommodation Layouts
fieldLayouts:
  e6e5ea3a-fb43-4843-bd9b-4e7203af27cc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1ae0ca48-e9ff-4b0a-aaba-9e8e23627850 # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: adf0f051-7f8a-40c5-b180-5fd371f68011
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 78cae37d-a45a-4f37-ad52-6420abc15846 # Headline
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81913101-5d72-4e11-ada3-cf4557571071
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e88d3e26-82c6-4157-b307-7fc5836aef6d # Description
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0429c96-f965-4917-a6e7-7c4908ec487f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 75142043-eb0f-4f28-952a-5135d5146074
        userCondition: null
fields:
  1ae0ca48-e9ff-4b0a-aaba-9e8e23627850: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  78cae37d-a45a-4f37-ad52-6420abc15846: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e88d3e26-82c6-4157-b307-7fc5836aef6d: # Description
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: null
    name: Description
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      characterLimit: null
      ckeConfig: 4dc3cdd6-aaf2-421a-bd6c-aaa6de96e874 # Default
      columnType: text
      defaultTransform: null
      purifierConfig: null
      purifyHtml: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      showWordCount: false
      sourceEditingGroups: '*'
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: accommodationLayout
name: 'Accommodation Layout'
sortOrder: 1
