field: a9d68e9a-5656-4fb6-b894-e9de89f44a74 # Hole-by-Hole Button
fieldLayouts:
  a5613ebf-c413-4b33-918a-97c15c2bd3ad:
    tabs:
      -
        elements:
          -
            fieldUid: 73d0f7c4-cc1c-4018-9fdd-a049d964ad1f # Button Text
            instructions: null
            label: null
            required: 1
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b227f4d1-65be-4007-a1ac-a25781b6e254 # Button URL
            instructions: null
            label: null
            required: 1
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  73d0f7c4-cc1c-4018-9fdd-a049d964ad1f: # Button Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: ''
    name: 'Button Text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b227f4d1-65be-4007-a1ac-a25781b6e254: # Button URL
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: buttonUrl
    instructions: ''
    name: 'Button URL'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: button
name: Button
sortOrder: 1
