field: 5fd92c59-65ac-442f-883a-e5d8d867ed86 # Content Block
fieldLayouts:
  27234b37-e75c-4776-8356-86661bf1f0aa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 63fb01ad-6b5a-4cff-a65e-bcf1c4f4db11 # Headline
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba893264-4224-4a07-9c7f-80995e14e877
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8b26cdc7-ea7e-4875-9eb9-ed4bbac17bd0 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 34040386-4184-4c4c-af14-ea99ecb08bec
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 814f1a4f-84ee-4fe3-8342-c04f4d1051da # Link Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a76468d-b0a4-444b-b1ff-c657a9d96da3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 85ac2980-6656-430b-a5af-ec8d3411d678 # Link URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4435860c-bdbd-495c-9ef9-549f208bc2dd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 72f34955-1dd3-4a97-af98-47dc4bf11c0b
        userCondition: null
fields:
  8b26cdc7-ea7e-4875-9eb9-ed4bbac17bd0: # Body
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: null
    name: Body
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      characterLimit: null
      ckeConfig: 4dc3cdd6-aaf2-421a-bd6c-aaa6de96e874 # Default
      columnType: text
      defaultTransform: null
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      showWordCount: false
      sourceEditingGroups: '*'
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  63fb01ad-6b5a-4cff-a65e-bcf1c4f4db11: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  85ac2980-6656-430b-a5af-ec8d3411d678: # Link URL
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: linkUrl
    instructions: null
    name: 'Link URL'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  814f1a4f-84ee-4fe3-8342-c04f4d1051da: # Link Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: linkText
    instructions: null
    name: 'Link Text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: contentBlock
name: Content
sortOrder: 1
