field: 5fd92c59-65ac-442f-883a-e5d8d867ed86 # Content Block
fieldLayouts:
  27234b37-e75c-4776-8356-86661bf1f0aa:
    tabs:
      -
        elements:
          -
            fieldUid: 63fb01ad-6b5a-4cff-a65e-bcf1c4f4db11 # Headline
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8b26cdc7-ea7e-4875-9eb9-ed4bbac17bd0 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 814f1a4f-84ee-4fe3-8342-c04f4d1051da # Link Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 85ac2980-6656-430b-a5af-ec8d3411d678 # Link URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  8b26cdc7-ea7e-4875-9eb9-ed4bbac17bd0: # Body
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: ''
    name: Body
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      ckeConfig: 4dc3cdd6-aaf2-421a-bd6c-aaa6de96e874 # Default
      columnType: text
      defaultTransform: ''
      enableSourceEditingForNonAdmins: true
      purifierConfig: ''
      purifyHtml: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  63fb01ad-6b5a-4cff-a65e-bcf1c4f4db11: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  85ac2980-6656-430b-a5af-ec8d3411d678: # Link URL
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: linkUrl
    instructions: ''
    name: 'Link URL'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  814f1a4f-84ee-4fe3-8342-c04f4d1051da: # Link Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: linkText
    instructions: ''
    name: 'Link Text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: contentBlock
name: Content
sortOrder: 1
