field: 8d3a52a0-3ef6-4c6f-a812-1b9972d643d9 # Apply Callout
fieldLayouts:
  1325dbcd-368a-4480-b956-20682912043c:
    tabs:
      -
        elements:
          -
            fieldUid: 40372289-dc21-49a5-8fde-84b1b64f4c69 # Headline
            instructions: null
            label: null
            required: 1
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7a261b1e-d387-4b69-aa5b-4a21ed282daf # Body
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d238cda2-b052-4d87-ac6b-67b58f334729 # Link Text
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fd799323-b5cd-4385-92ab-49dfe5e15759 # Link URL
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  7a261b1e-d387-4b69-aa5b-4a21ed282daf: # Body
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: ''
    name: Body
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      ckeConfig: 4dc3cdd6-aaf2-421a-bd6c-aaa6de96e874 # Default
      columnType: text
      defaultTransform: ''
      enableSourceEditingForNonAdmins: true
      purifierConfig: ''
      purifyHtml: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  40372289-dc21-49a5-8fde-84b1b64f4c69: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d238cda2-b052-4d87-ac6b-67b58f334729: # Link Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: linkText
    instructions: ''
    name: 'Link Text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  fd799323-b5cd-4385-92ab-49dfe5e15759: # Link URL
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: linkUrl
    instructions: ''
    name: 'Link URL'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: contentBlock
name: 'Content Block'
sortOrder: 1
