field: 13f7924e-3e35-4361-aa55-b3df417f8631 # Home Intro
fieldLayouts:
  afa76260-5c76-44e3-873c-5882fd5dfaea:
    tabs:
      -
        elements:
          -
            fieldUid: 474ced41-234f-42f8-8654-ea3aaf7d4018 # Background Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 50b6f61a-8262-47d0-b09c-b7b2a0fcd920 # Headline
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 70584659-d0e8-4e6d-84c6-2f748e564a52 # Label
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: aaa2c471-b3eb-4a61-b353-2bb1d712c4f6 # Body
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 697114a4-18e6-4819-90f5-51be64ff46c4 # Button Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9c0bdaed-ba3d-45a0-a4cb-bdd5ca1d4cfe # Button URL
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ebe1e8e8-af10-40ac-8a0d-b531441539e6 # CTA
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  9c0bdaed-ba3d-45a0-a4cb-bdd5ca1d4cfe: # Button URL
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: buttonUrl
    instructions: ''
    name: 'Button URL'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  50b6f61a-8262-47d0-b09c-b7b2a0fcd920: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  474ced41-234f-42f8-8654-ea3aaf7d4018: # Background Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: backgroundImage
    instructions: ''
    name: 'Background Image'
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  697114a4-18e6-4819-90f5-51be64ff46c4: # Button Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: ''
    name: 'Button Text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  70584659-d0e8-4e6d-84c6-2f748e564a52: # Label
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: 'The text that is in the watermark effect'
    name: Label
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  aaa2c471-b3eb-4a61-b353-2bb1d712c4f6: # Body
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: ''
    name: Body
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  ebe1e8e8-af10-40ac-8a0d-b531441539e6: # CTA
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: cta
    instructions: 'NOTE: Phone number is brought in dynamically via the phone number in the Globals->Contact Information'
    name: CTA
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: contentBlock
name: 'Content Block'
sortOrder: 1
