field: d5cd7453-de1f-4641-9290-c5d728857cb9 # Course History
fieldLayouts:
  fa5c8404-5f6c-4870-9e27-559fc0fdcf79:
    tabs:
      -
        elements:
          -
            fieldUid: e99bb281-fc38-4e61-8d38-d19934bf170a # Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4b4c2ec7-bb72-4d4e-91e8-1347888be1da # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 53576eb0-38c9-4375-acd7-fb7d17c8f361 # Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ef70e1b7-cf97-43cd-a65e-52ccff3a11b2 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ed71610d-27b5-4aa6-a099-2437d809df35 # CTA
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4b4c2ec7-bb72-4d4e-91e8-1347888be1da: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  53576eb0-38c9-4375-acd7-fb7d17c8f361: # Label
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: 'The text that is in the watermark effect'
    name: Label
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e99bb281-fc38-4e61-8d38-d19934bf170a: # Background Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: backgroundImage
    instructions: ''
    name: 'Background Image'
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Add an Image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  ed71610d-27b5-4aa6-a099-2437d809df35: # CTA
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: cta
    instructions: 'NOTE: Phone number is brought in dynamically via the phone number in the Globals->Contact Information'
    name: CTA
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ef70e1b7-cf97-43cd-a65e-52ccff3a11b2: # Body
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: ''
    name: Body
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      ckeConfig: 8c62cfca-5a41-451c-9f8e-1272591144b7 # Standard
      columnType: text
      defaultTransform: ''
      enableSourceEditingForNonAdmins: true
      purifierConfig: ''
      purifyHtml: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: courseHistoryBlock
name: 'Course History Block'
sortOrder: 1
