field: d5cd7453-de1f-4641-9290-c5d728857cb9 # Course History
fieldLayouts:
  fa5c8404-5f6c-4870-9e27-559fc0fdcf79:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e99bb281-fc38-4e61-8d38-d19934bf170a # Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3dcb08aa-4497-4300-b509-67306f05d00a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4b4c2ec7-bb72-4d4e-91e8-1347888be1da # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 437650d5-15c3-4c60-8505-c1984f6da034
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 53576eb0-38c9-4375-acd7-fb7d17c8f361 # Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c9ce974-0559-473c-9abf-29af45e3fd80
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ef70e1b7-cf97-43cd-a65e-52ccff3a11b2 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2bbf0e2d-2280-412f-bc02-0a031c0598ad
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ed71610d-27b5-4aa6-a099-2437d809df35 # CTA
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef7c7d16-1064-47c1-8494-93bc776d0843
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b2d10f24-d7d0-4bfa-9342-3fcd5a8c1ce8
        userCondition: null
fields:
  4b4c2ec7-bb72-4d4e-91e8-1347888be1da: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  53576eb0-38c9-4375-acd7-fb7d17c8f361: # Label
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: 'The text that is in the watermark effect'
    name: Label
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e99bb281-fc38-4e61-8d38-d19934bf170a: # Background Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: backgroundImage
    instructions: null
    name: 'Background Image'
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      restrictedLocationSubpath: null
      selectionLabel: 'Add an Image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  ed71610d-27b5-4aa6-a099-2437d809df35: # CTA
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: cta
    instructions: 'NOTE: Phone number is brought in dynamically via the phone number in the Globals->Contact Information'
    name: CTA
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ef70e1b7-cf97-43cd-a65e-52ccff3a11b2: # Body
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: null
    name: Body
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      characterLimit: null
      ckeConfig: 8c62cfca-5a41-451c-9f8e-1272591144b7 # Standard
      columnType: text
      defaultTransform: null
      purifierConfig: null
      purifyHtml: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      showWordCount: false
      sourceEditingGroups: '*'
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: courseHistoryBlock
name: 'Course History Block'
sortOrder: 1
