field: df2fb927-6c87-4678-9950-d3a004411ca8 # Courses
fieldLayouts:
  0222c75e-dfcb-456d-8e59-b66fe2a71732:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 757ad3bc-3bc1-4828-91ee-a35c04d93e82 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77e6b44b-4cbd-4bc8-aac4-42e4a834c652
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0a870800-b231-49d9-9cb3-c79728880aa0 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 140a7035-8f27-4058-8102-6c03c3d35013
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e7f3e789-e3c9-46ee-add0-1122214d324c # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 847e28c4-fabb-4de8-b4a4-bb5d74b48914
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7669c804-7d73-44b8-b828-ac58297fdab9
        userCondition: null
fields:
  0a870800-b231-49d9-9cb3-c79728880aa0: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  757ad3bc-3bc1-4828-91ee-a35c04d93e82: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      restrictedLocationSubpath: null
      selectionLabel: 'Add an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  e7f3e789-e3c9-46ee-add0-1122214d324c: # Button
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: button
    instructions: null
    name: Button
    searchable: true
    settings:
      allowCustomText: true
      allowTarget: false
      defaultText: null
      selectLinkText: ''
      types:
        __assoc__:
          -
            - presseddigital\linkit\models\Email
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Phone
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Url
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
                -
                  - allowAlias
                  - '1'
                -
                  - allowMailto
                  - '1'
                -
                  - allowHash
                  - '1'
                -
                  - allowPaths
                  - '1'
          -
            - presseddigital\linkit\models\Twitter
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Facebook
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Instagram
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\LinkedIn
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Entry
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  -
                    - 'section:cd118c39-5937-4705-b0db-2cb2bb0b7e9b' # Courses
                -
                  - customSelectionLabel
                  - ''
          -
            - presseddigital\linkit\models\Category
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - ''
          -
            - presseddigital\linkit\models\Asset
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - ''
          -
            - presseddigital\linkit\models\User
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - ''
                -
                  - userPath
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: presseddigital\linkit\fields\LinkitField
handle: course
name: Course
sortOrder: 1
