field: 0e38621c-2421-4292-ae5b-aa86828ee673 # Linked List
fieldLayouts:
  faf6fedb-b25d-4979-8e98-dd59fa8e910a:
    tabs:
      -
        elements:
          -
            fieldUid: 4abaa592-1034-44af-8c86-16ffeb72caac # Description
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4abaa592-1034-44af-8c86-16ffeb72caac: # Description
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: ''
    name: Description
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      ckeConfig: 4dc3cdd6-aaf2-421a-bd6c-aaa6de96e874 # Default
      columnType: text
      defaultTransform: ''
      enableSourceEditingForNonAdmins: true
      purifierConfig: null
      purifyHtml: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: description
name: Description
sortOrder: 2
