field: d72e767d-d3ea-4731-8e82-2981e56059c7 # Local Airports
fieldLayouts:
  79129ec3-add6-48ef-8cab-ce80592f7f4a:
    tabs:
      -
        elements:
          -
            fieldUid: c73fb067-a5f1-44c7-9db5-2813a46b689d # Description
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  c73fb067-a5f1-44c7-9db5-2813a46b689d: # Description
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: ''
    name: Description
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: description
name: Description
sortOrder: 3
