field: 88856313-68a9-44fd-8849-c2e1cecb3695 # Featured Awards
fieldLayouts:
  db551f86-e1d4-4c88-8536-7a8c71186c76:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bf4ceaad-c57f-48fb-9b8d-f611cd99f684 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: edc6c7fb-e22f-4cb8-97f2-d8ee602a9aa3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 45bc99ca-410d-4b39-8f27-af81c81e4b67 # Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8039dd8d-f6fd-4c75-8066-034b50f085b7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 682d4143-3055-4236-a72f-d8490d82a088 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d389c9d0-9009-4da7-9bf2-6769e67b74d6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fbf63f47-0d11-40d0-9889-18017e89451a # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 25734637-650d-4158-974f-aca27fac8783
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 387eef86-7728-4b0f-84cc-190f9b0aa3d0
        userCondition: null
fields:
  45bc99ca-410d-4b39-8f27-af81c81e4b67: # Name
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: awardName
    instructions: null
    name: Name
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  682d4143-3055-4236-a72f-d8490d82a088: # Description
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: awardDescription
    instructions: null
    name: Description
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      characterLimit: null
      ckeConfig: 49a3924a-193d-40e7-ac57-4709787234ed # Simple
      columnType: text
      defaultTransform: null
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      showWordCount: false
      sourceEditingGroups: '*'
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  bf4ceaad-c57f-48fb-9b8d-f611cd99f684: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: awardImage
    instructions: null
    name: Image
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      restrictedLocationSubpath: null
      selectionLabel: 'Add an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  fbf63f47-0d11-40d0-9889-18017e89451a: # Link
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: awardLink
    instructions: null
    name: Link
    searchable: true
    settings:
      allowCustomText: true
      allowTarget: true
      defaultText: null
      selectLinkText: ''
      types:
        __assoc__:
          -
            - presseddigital\linkit\models\Email
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Phone
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Url
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
                -
                  - allowAlias
                  - '1'
                -
                  - allowMailto
                  - '1'
                -
                  - allowHash
                  - '1'
                -
                  - allowPaths
                  - '1'
          -
            - presseddigital\linkit\models\Twitter
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Facebook
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Instagram
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\LinkedIn
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Entry
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  -
                    - 'section:0c9fc74f-f5c7-4b5f-8b80-8ea98aa0999e' # Accommodations
                    - 'section:cd118c39-5937-4705-b0db-2cb2bb0b7e9b' # Courses
                    - 'section:f02a0d8f-d625-405c-a782-87b045350b7f' # Dining
                    - 'section:19d04551-214f-4e9b-9a5e-ff66d6fe1028' # News
                    - singles
                    - 'section:3dfade29-0d50-45dd-9bf0-0b0a2fed7406' # Utility Pages
                -
                  - customSelectionLabel
                  - ''
          -
            - presseddigital\linkit\models\Category
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - ''
          -
            - presseddigital\linkit\models\Asset
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - ''
          -
            - presseddigital\linkit\models\User
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - ''
                -
                  - userPath
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: presseddigital\linkit\fields\LinkitField
handle: featuredAward
name: 'Featured Award'
sortOrder: 1
