field: d838d1b8-1c0e-469d-bb0d-e1a9d81413fc # General Contacts
fieldLayouts:
  557e157e-1fa6-4523-a117-80dc3d31969c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b69e2489-a432-4e27-ae4b-af86cd023ac2 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf0ffc44-6344-46d0-81f1-fc1d8198afb3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1e5a632d-5444-4c79-9ee0-5c924f29c0d6 # General Contacts
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d246784-e4fe-44f2-aa67-6088f196814a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c22084f0-7727-46e2-91c8-2bdcdbb82d83
        userCondition: null
fields:
  1e5a632d-5444-4c79-9ee0-5c924f29c0d6: # General Contacts
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: generalContacts
    instructions: null
    name: 'General Contacts'
    searchable: true
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - handle
                  - label
                -
                  - heading
                  - Label
                -
                  - type
                  - singleline
                -
                  - width
                  - ''
          -
            - col2
            -
              __assoc__:
                -
                  - handle
                  - phone
                -
                  - heading
                  - Phone
                -
                  - type
                  - singleline
                -
                  - width
                  - ''
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
      maxRows: null
      minRows: null
      staticRows: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  b69e2489-a432-4e27-ae4b-af86cd023ac2: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: generalContacts
name: 'General Contacts'
sortOrder: 1
