field: d72e767d-d3ea-4731-8e82-2981e56059c7 # Local Airports
fieldLayouts:
  1df63586-1927-4a74-9164-60cf3935d0a2:
    tabs:
      -
        elements:
          -
            fieldUid: a2401124-246c-4550-8353-d067b0edddf3 # Headline
            instructions: null
            label: null
            required: 1
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  a2401124-246c-4550-8353-d067b0edddf3: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: headline
name: Headline
sortOrder: 1
