field: d72e767d-d3ea-4731-8e82-2981e56059c7 # Local Airports
fieldLayouts:
  1df63586-1927-4a74-9164-60cf3935d0a2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a2401124-246c-4550-8353-d067b0edddf3 # Headline
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6de1ba56-4c61-499d-9b86-c58fdd8642cf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9cd3a5e0-49f8-4e71-833f-c13b54ad9116
        userCondition: null
fields:
  a2401124-246c-4550-8353-d067b0edddf3: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: headline
name: Headline
sortOrder: 1
