field: 58d379a7-f464-4baf-8555-e5b71c12d289 # Intro Block
fieldLayouts:
  4d627346-d89d-4ae9-9223-ea57605acf36:
    tabs:
      -
        elements:
          -
            fieldUid: 043b0e31-2a28-45c5-853c-2723fe2ce724 # Headline
            instructions: null
            label: null
            required: 1
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7bbf65b1-050d-451a-a681-13b0bbe158a1 # Body
            instructions: null
            label: null
            required: 1
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  7bbf65b1-050d-451a-a681-13b0bbe158a1: # Body
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: ''
    name: Body
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  043b0e31-2a28-45c5-853c-2723fe2ce724: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: introBlock
name: 'Intro Block'
sortOrder: 1
