field: 9432c02d-3660-469e-af4c-461baccc92ce # CTA Footer
fieldLayouts:
  dbf7c039-b08e-4daa-b4bb-f60906bcf9bf:
    tabs:
      -
        elements:
          -
            fieldUid: a152dece-e53d-4f4f-b5ee-a5761cdefe3b # Link
            instructions: null
            label: null
            required: 1
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  a152dece-e53d-4f4f-b5ee-a5761cdefe3b: # Link
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: ctaLink
    instructions: ''
    name: Link
    searchable: true
    settings:
      allowCustomText: ''
      allowTarget: ''
      defaultText: ''
      selectLinkText: ''
      types:
        __assoc__:
          -
            - presseddigital\linkit\models\Email
            -
              __assoc__:
                -
                  - enabled
                  - 1
          -
            - presseddigital\linkit\models\Phone
            -
              __assoc__:
                -
                  - enabled
                  - 1
          -
            - presseddigital\linkit\models\Url
            -
              __assoc__:
                -
                  - enabled
                  - 1
          -
            - presseddigital\linkit\models\Entry
            -
              __assoc__:
                0:
                  - enabled
                  - 1
                2:
                  - sources
                  - '*'
                3:
                  - customSelectionLabel
                  - 'Select an entry'
          -
            - presseddigital\linkit\models\Category
            -
              __assoc__:
                0:
                  - enabled
                  - 1
                2:
                  - sources
                  - '*'
                3:
                  - customSelectionLabel
                  - 'Select a category'
          -
            - presseddigital\linkit\models\Asset
            -
              __assoc__:
                0:
                  - enabled
                  - 1
                2:
                  - sources
                  - '*'
                3:
                  - customSelectionLabel
                  - 'Select an asset'
    translationKeyFormat: null
    translationMethod: none
    type: presseddigital\linkit\fields\LinkitField
handle: link
name: Link
sortOrder: 1
