field: 9432c02d-3660-469e-af4c-461baccc92ce # CTA Footer
fieldLayouts:
  dbf7c039-b08e-4daa-b4bb-f60906bcf9bf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a152dece-e53d-4f4f-b5ee-a5761cdefe3b # Link
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f41e49b-c739-44a6-a842-b018c71dec8b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c2de253b-6355-4ed7-89bb-9c97211d12b3
        userCondition: null
fields:
  a152dece-e53d-4f4f-b5ee-a5761cdefe3b: # Link
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: ctaLink
    instructions: null
    name: Link
    searchable: true
    settings:
      allowCustomText: false
      allowTarget: false
      defaultText: null
      selectLinkText: ''
      types:
        __assoc__:
          -
            - presseddigital\linkit\models\Email
            -
              __assoc__:
                -
                  - enabled
                  - 1
          -
            - presseddigital\linkit\models\Phone
            -
              __assoc__:
                -
                  - enabled
                  - 1
          -
            - presseddigital\linkit\models\Url
            -
              __assoc__:
                -
                  - enabled
                  - 1
          -
            - presseddigital\linkit\models\Entry
            -
              __assoc__:
                0:
                  - enabled
                  - 1
                2:
                  - sources
                  - '*'
                3:
                  - customSelectionLabel
                  - 'Select an entry'
          -
            - presseddigital\linkit\models\Category
            -
              __assoc__:
                0:
                  - enabled
                  - 1
                2:
                  - sources
                  - '*'
                3:
                  - customSelectionLabel
                  - 'Select a category'
          -
            - presseddigital\linkit\models\Asset
            -
              __assoc__:
                0:
                  - enabled
                  - 1
                2:
                  - sources
                  - '*'
                3:
                  - customSelectionLabel
                  - 'Select an asset'
    translationKeyFormat: null
    translationMethod: none
    type: presseddigital\linkit\fields\LinkitField
handle: link
name: Link
sortOrder: 1
