field: d72e767d-d3ea-4731-8e82-2981e56059c7 # Local Airports
fieldLayouts:
  c8ceb4dd-658f-4f3a-a350-f46c3db92a47:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3e7bdbb4-2ac0-4b7f-93b9-ea27df0416b6 # Linked List
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 205157c2-d043-4df6-8c21-94fcbf568dd1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3bcfaf94-fad8-4577-b150-a9c5301cfbd2
        userCondition: null
fields:
  3e7bdbb4-2ac0-4b7f-93b9-ea27df0416b6: # Linked List
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: linkedList
    instructions: null
    name: 'Linked List'
    searchable: true
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - handle
                  - linkText
                -
                  - heading
                  - 'Link Text'
                -
                  - type
                  - singleline
                -
                  - width
                  - ''
          -
            - col2
            -
              __assoc__:
                -
                  - handle
                  - linkUrl
                -
                  - heading
                  - 'Link URL'
                -
                  - type
                  - singleline
                -
                  - width
                  - ''
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
      maxRows: null
      minRows: null
      staticRows: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
handle: linkedList
name: 'Linked List'
sortOrder: 2
