field: 0e38621c-2421-4292-ae5b-aa86828ee673 # Linked List
fieldLayouts:
  45466537-869f-4fb4-9e20-e684c498f7ef:
    tabs:
      -
        elements:
          -
            fieldUid: 0f863fe3-b46b-4804-a61e-1b62c737d2f7 # Linked List
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0f863fe3-b46b-4804-a61e-1b62c737d2f7: # Linked List
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: linkedList
    instructions: ''
    name: 'Linked List'
    searchable: true
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - handle
                  - linkText
                -
                  - heading
                  - 'Link Text'
                -
                  - type
                  - singleline
                -
                  - width
                  - ''
          -
            - col2
            -
              __assoc__:
                -
                  - handle
                  - linkUrl
                -
                  - heading
                  - 'Link URL'
                -
                  - type
                  - singleline
                -
                  - width
                  - ''
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
      maxRows: null
      minRows: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
handle: linkedList
name: 'Linked List'
sortOrder: 3
