field: 961562fa-ae3d-4a9d-b304-43d727329d53 # Private Event Options
fieldLayouts:
  036dcd0f-62aa-4d41-954f-9d8109c35872:
    tabs:
      -
        elements:
          -
            fieldUid: 18d710bf-237c-4a66-9707-1a63cc543871 # Headline
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 669373c9-7338-40ff-b910-b4e164a5c4e4 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a0ab0cd8-2161-45c5-bf59-4e2d5eef8703 # Details List
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ea52dcf4-0ef2-443e-b70d-7ca566b249bb # Menus
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 894ceebd-0a7f-4a96-a00b-87e7a5a69aa1 # Gallery
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  18d710bf-237c-4a66-9707-1a63cc543871: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  894ceebd-0a7f-4a96-a00b-87e7a5a69aa1: # Gallery
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: gallery
    instructions: ''
    name: Gallery
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Add an Image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  669373c9-7338-40ff-b910-b4e164a5c4e4: # Description
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: ''
    name: Description
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  a0ab0cd8-2161-45c5-bf59-4e2d5eef8703: # Details List
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: detailsList
    instructions: ''
    name: 'Details List'
    searchable: true
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Label
                -
                  - handle
                  - label
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - Detail
                -
                  - handle
                  - detail
                -
                  - width
                  - ''
                -
                  - type
                  - multiline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
      maxRows: ''
      minRows: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  ea52dcf4-0ef2-443e-b70d-7ca566b249bb: # Menus
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: menus
    instructions: ''
    name: Menus
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - 870d5282-0576-4680-aa71-d2d5147444a2 # Link Text
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - ee9dcd04-b2cf-416c-86a4-45519eae43ef # Link Url
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_38_menus_1}}'
      fieldLayout: row
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: 'Add a Menu'
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: option
name: Option
sortOrder: 1
