field: e1b08e83-a1f1-4c82-9f19-ffa70434df89 # Dining Options
fieldLayouts:
  53fab780-65a6-42f8-bc88-a80b60549608:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2cbe1637-1cb0-4d03-a7f0-61e14788e974 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ace1e99-554f-4775-900b-421b4b04b2e4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 62f60a54-795c-49ce-bfd2-42a6f6888d92 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 865d6a2c-bba3-4ffa-a8b8-08942cc2707e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d08f7f35-3977-48a8-8fea-d79697d19e1e # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f4650256-9f6d-4957-8db9-77e843d01a51
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 795d3c54-ebb3-4576-b04b-17046dd1da7a # Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 520a319e-86fa-4069-8ebe-c1f99670ca1a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9f55b922-8eb2-447b-b877-f892b243f70f # Details
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 992c4300-a01b-46ed-b46b-f1019269eb00
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5e07300e-37d4-4d70-a99e-997b495703e6
        userCondition: null
fields:
  2cbe1637-1cb0-4d03-a7f0-61e14788e974: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      restrictedLocationSubpath: null
      selectionLabel: 'Add an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  9f55b922-8eb2-447b-b877-f892b243f70f: # Details
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: details
    instructions: null
    name: Details
    searchable: true
    settings:
      blockTypeFields: 0
      changedFieldIndicator: null
      columns:
        __assoc__:
          -
            - 6ef8762f-934c-4150-9f3a-c723ee40b0b8 # Label
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - a61b6ef6-9c03-4a39-8592-63f661928329 # Detail
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_51_details_1}}'
      fieldLayout: table
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: 'Add a detail'
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  62f60a54-795c-49ce-bfd2-42a6f6888d92: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  795d3c54-ebb3-4576-b04b-17046dd1da7a: # Buttons
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: buttons
    instructions: null
    name: Buttons
    searchable: true
    settings:
      blockTypeFields: 0
      changedFieldIndicator: null
      columns:
        __assoc__:
          -
            - e433d8bb-8a45-4fc3-b61c-14241393d931 # Button
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_51_buttons_1}}'
      fieldLayout: table
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: 'Add a button'
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  d08f7f35-3977-48a8-8fea-d79697d19e1e: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      characterLimit: null
      ckeConfig: 4dc3cdd6-aaf2-421a-bd6c-aaa6de96e874 # Default
      columnType: text
      defaultTransform: null
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      showWordCount: false
      sourceEditingGroups: '*'
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: option
name: Option
sortOrder: 1
