field: 716abbda-6a26-45cc-b52c-901463010380 # Page Links
fieldLayouts:
  58a115df-db81-4c6e-8b70-bf3164aca06c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f0dca59d-239c-4146-813f-2b147b0ce790 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d61cb008-1ba9-4e1c-b2ab-715b49aeb2f9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2e89d38a-eaec-4b2b-943f-d94ba49050d0 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd262341-ac09-424c-a095-46f0f1afe3a7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: acea35fc-de86-48eb-b5dc-f5f07375d2cb # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bcc543c9-150f-4974-9891-0dfcb5cdbae3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1e939607-791e-4d0d-9e90-da7db5cb3e58 # Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0a20527-21de-42c2-8686-5a7a1440a61f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 79bba8c2-edf7-4175-a0c7-e31f1df8cace
        userCondition: null
fields:
  1e939607-791e-4d0d-9e90-da7db5cb3e58: # Buttons
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: buttons
    instructions: null
    name: Buttons
    searchable: true
    settings:
      blockTypeFields: 0
      changedFieldIndicator: null
      columns:
        __assoc__:
          -
            - 7f33d691-0281-4de9-8404-38467e35d592 # Button
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_52_buttons_1}}'
      fieldLayout: table
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: 'Add a row'
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  2e89d38a-eaec-4b2b-943f-d94ba49050d0: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  acea35fc-de86-48eb-b5dc-f5f07375d2cb: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      characterLimit: null
      ckeConfig: 4dc3cdd6-aaf2-421a-bd6c-aaa6de96e874 # Default
      columnType: text
      defaultTransform: null
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      showWordCount: false
      sourceEditingGroups: '*'
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  f0dca59d-239c-4146-813f-2b147b0ce790: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      restrictedLocationSubpath: null
      selectionLabel: 'Add an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: pageLink
name: 'Page Link'
sortOrder: 1
