field: f6f57ddb-d979-455a-8803-923779a0aece # Accommodation Pricing
fieldLayouts:
  163864e2-4c10-4a52-9285-ca3b83c9dea4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1c73a949-4efb-4981-9845-5fc07773a52e # Tab Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 038d79c9-9115-48b7-b9b3-124039d454e0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3046ec83-6114-4d56-9a73-383b7243bd8d # Pricing Table
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4441454a-80ef-4d9d-a84c-ce23826b7085
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4ab5842b-2eac-4ee9-9c9b-67194eda8f76 # Pricing Footer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7a747b2b-8290-4218-9fd1-cd0a7cf29748
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 95bdf0b9-6728-4e50-badf-be87860d5240 # Golf Add-On Pricing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 920d1386-7743-4dd5-8b22-a2ccaba5a486
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fb74ed20-6f42-439f-ae94-b2de2f856d24
        userCondition: null
fields:
  1c73a949-4efb-4981-9845-5fc07773a52e: # Tab Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: tabText
    instructions: null
    name: 'Tab Text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  4ab5842b-2eac-4ee9-9c9b-67194eda8f76: # Pricing Footer
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: pricingFooter
    instructions: null
    name: 'Pricing Footer'
    searchable: true
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Comment
                -
                  - handle
                  - comment
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
      maxRows: null
      minRows: null
      staticRows: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  95bdf0b9-6728-4e50-badf-be87860d5240: # Golf Add-On Pricing
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: golfAddOnPricing
    instructions: null
    name: 'Golf Add-On Pricing'
    searchable: true
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Label
                -
                  - handle
                  - label
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - 'Bluffs Price'
                -
                  - handle
                  - bluffsPrice
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col3
            -
              __assoc__:
                -
                  - heading
                  - 'South Course Price'
                -
                  - handle
                  - southCoursePrice
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
            -
              - col3
              - ''
      maxRows: null
      minRows: null
      staticRows: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  3046ec83-6114-4d56-9a73-383b7243bd8d: # Pricing Table
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: pricingTable
    instructions: null
    name: 'Pricing Table'
    searchable: true
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Label
                -
                  - handle
                  - label
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - Price
                -
                  - handle
                  - price
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
      maxRows: null
      minRows: null
      staticRows: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
handle: pricingTab
name: 'Pricing Tab'
sortOrder: 1
