field: f6f57ddb-d979-455a-8803-923779a0aece # Accommodation Pricing
fieldLayouts:
  163864e2-4c10-4a52-9285-ca3b83c9dea4:
    tabs:
      -
        elements:
          -
            fieldUid: 1c73a949-4efb-4981-9845-5fc07773a52e # Tab Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3046ec83-6114-4d56-9a73-383b7243bd8d # Pricing Table
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4ab5842b-2eac-4ee9-9c9b-67194eda8f76 # Pricing Footer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 95bdf0b9-6728-4e50-badf-be87860d5240 # Golf Add-On Pricing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1c73a949-4efb-4981-9845-5fc07773a52e: # Tab Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: tabText
    instructions: ''
    name: 'Tab Text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  4ab5842b-2eac-4ee9-9c9b-67194eda8f76: # Pricing Footer
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: pricingFooter
    instructions: ''
    name: 'Pricing Footer'
    searchable: true
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Comment
                -
                  - handle
                  - comment
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
      maxRows: ''
      minRows: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  95bdf0b9-6728-4e50-badf-be87860d5240: # Golf Add-On Pricing
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: golfAddOnPricing
    instructions: ''
    name: 'Golf Add-On Pricing'
    searchable: true
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Label
                -
                  - handle
                  - label
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - 'Bluffs Price'
                -
                  - handle
                  - bluffsPrice
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col3
            -
              __assoc__:
                -
                  - heading
                  - 'South Course Price'
                -
                  - handle
                  - southCoursePrice
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
            -
              - col3
              - ''
      maxRows: ''
      minRows: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  3046ec83-6114-4d56-9a73-383b7243bd8d: # Pricing Table
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: pricingTable
    instructions: ''
    name: 'Pricing Table'
    searchable: true
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Label
                -
                  - handle
                  - label
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - Price
                -
                  - handle
                  - price
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
      maxRows: ''
      minRows: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
handle: pricingTab
name: 'Pricing Tab'
sortOrder: 1
