field: cde13c4b-01bc-4465-ae64-8c0473b3931b # Rates
fieldLayouts:
  04387683-58e3-4625-81ac-eeb77c9a2df8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 947f4266-c25e-42b4-a78e-07321ff4e4d3 # Tab Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10dd4d5c-c28f-4b13-96e4-f740c60a205d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: eaa1ff40-1ac8-4150-8a7f-035477ce3bb8 # Pricing Table
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c3ca390-cf0e-47bc-b869-b9bb815fc45e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a47dfd63-9d5b-4709-bda4-d057450f6f56 # Pricing Footer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a0e0205-ce26-4a52-b5eb-1bd0acea0192
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2bd18b27-5fec-47e9-893c-a8c72737c09c
        userCondition: null
fields:
  947f4266-c25e-42b4-a78e-07321ff4e4d3: # Tab Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: tabText
    instructions: null
    name: 'Tab Text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a47dfd63-9d5b-4709-bda4-d057450f6f56: # Pricing Footer
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: pricingFooter
    instructions: null
    name: 'Pricing Footer'
    searchable: true
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - handle
                  - comment
                -
                  - heading
                  - Comment
                -
                  - type
                  - singleline
                -
                  - width
                  - ''
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
      maxRows: null
      minRows: null
      staticRows: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  eaa1ff40-1ac8-4150-8a7f-035477ce3bb8: # Pricing Table
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: pricingTable
    instructions: null
    name: 'Pricing Table'
    searchable: true
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - handle
                  - label
                -
                  - heading
                  - Label
                -
                  - type
                  - singleline
                -
                  - width
                  - ''
          -
            - col2
            -
              __assoc__:
                -
                  - handle
                  - price
                -
                  - heading
                  - Price
                -
                  - type
                  - singleline
                -
                  - width
                  - ''
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
      maxRows: null
      minRows: null
      staticRows: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
handle: pricingTab
name: 'Pricing Tab'
sortOrder: 1
