field: 7da47c32-f9fb-4a89-9c30-22238ac588bd # Slope Tables
fieldLayouts:
  e4fa1745-424a-4a04-8c35-8d438a859872:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cfc96944-eb9c-41e9-a313-1ac2fac8eec2 # Table
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b49c5f7e-936b-441f-899e-e22a7d8f2d4f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 292878d2-db72-48b0-b097-c63ad3672d06
        userCondition: null
fields:
  cfc96944-eb9c-41e9-a313-1ac2fac8eec2: # Table
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: table
    instructions: null
    name: Table
    searchable: true
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - handle
                  - label
                -
                  - heading
                  - Label
                -
                  - type
                  - singleline
                -
                  - width
                  - ''
          -
            - col2
            -
              __assoc__:
                -
                  - handle
                  - rating
                -
                  - heading
                  - Rating
                -
                  - type
                  - singleline
                -
                  - width
                  - ''
          -
            - col3
            -
              __assoc__:
                -
                  - handle
                  - slope
                -
                  - heading
                  - Slope
                -
                  - type
                  - singleline
                -
                  - width
                  - ''
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
            -
              - col3
              - ''
      maxRows: null
      minRows: null
      staticRows: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
handle: slopeTable
name: 'Slope Table'
sortOrder: 1
