field: b67c258a-ab57-4bce-8a04-dd8aa2b891dd # Executive Team Row
fieldLayouts:
  585e3cce-ec73-4a8b-9751-fc573a385677:
    tabs:
      -
        elements:
          -
            fieldUid: 8901e690-f63a-4540-a2f6-9b4d1f0f50a2 # Headshot
            instructions: null
            label: null
            required: 1
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 17e2c1dd-aecc-48d0-bdee-ee898abe0a3b # Name
            instructions: null
            label: null
            required: 1
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 36543e5f-0c33-43d5-a9c4-c024fadc72e4 # Job Title
            instructions: null
            label: null
            required: 1
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d094cea2-a9d5-492a-9663-e179d0878780 # Email
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  17e2c1dd-aecc-48d0-bdee-ee898abe0a3b: # Name
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: teamMemberName
    instructions: ''
    name: Name
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8901e690-f63a-4540-a2f6-9b4d1f0f50a2: # Headshot
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: headshot
    instructions: ''
    name: Headshot
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  36543e5f-0c33-43d5-a9c4-c024fadc72e4: # Job Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: jobTitle
    instructions: ''
    name: 'Job Title'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d094cea2-a9d5-492a-9663-e179d0878780: # Email
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: email
    instructions: ''
    name: Email
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: teamMember
name: 'Team Member'
sortOrder: 1
