field: ebccde73-cbc1-4e05-8a10-b7c5afff0f35 # Video
fieldLayouts:
  510aad00-c8ef-48c1-8164-c58b4dbc4556:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f3cf412c-f5d5-463b-b63a-7b34943ecef5 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6063df3-f96e-4451-80fb-dc035a6d9ae3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8f377780-b7ab-44cf-8b1e-47b3d95753c1 # Background Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93213438-8616-4414-8744-5550c570bc39
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0d624f18-bf3c-49b5-becb-533c2185c9b9 # Button Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9cad30bc-5f84-4810-b56f-b04b97b42d6a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 63a1bc53-bfb2-49ae-9d5d-664627389036 # Video Embed
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d00ccc3b-a56b-418d-95f9-e14d8997d670
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 52298a55-a873-430d-be8a-19e40f09b7b0
        userCondition: null
fields:
  0d624f18-bf3c-49b5-becb-533c2185c9b9: # Button Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: null
    name: 'Button Text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8f377780-b7ab-44cf-8b1e-47b3d95753c1: # Background Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: backgroundImage
    instructions: null
    name: 'Background Image'
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  63a1bc53-bfb2-49ae-9d5d-664627389036: # Video Embed
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: videoEmbed
    instructions: 'Paste the full embed code for your video from Youtube or Vimeo. When you paste from Vimeo, but sure not to include the extra link and text. Just simply the iframe code.'
    name: 'Video Embed'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f3cf412c-f5d5-463b-b63a-7b34943ecef5: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: video
name: Video
sortOrder: 1
