fieldLayouts:
  adc6d8af-a523-4842-91fd-f873c0d9db0c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 339050e8-eed4-41e6-ace3-2744abc5bf47
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8991f73e-fc38-46e6-a4db-49b9f6697e67 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8ce9c7f4-de19-4624-bfe5-aff32d2df7c0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0d4713d1-5055-456d-b451-5eacbc986e7d # Banner Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a8559fe6-3d0b-4466-9790-3306589b0d81
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 55488e76-80a0-494a-8adb-4f6cd00535a8 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f6000bc-739c-4a53-a5e5-7d2f8e4a3092
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0a2670e7-65b0-45b5-96be-318580462d30 # Featured Awards
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba597004-822e-457d-adaf-bbda8b3191c1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 243afeaf-346c-4b8b-af89-9bd633f855e6 # General Awards
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0f71d5f-76e5-4a18-a857-466b94368c08
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 42a722bb-fc3e-4321-996c-5c83263531ef
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2c18936f-5777-4b43-9390-20d3b4f26d51 # Metadata
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f4ffc798-8df3-4818-9972-f1fc79fc10df
            userCondition: null
            warning: null
            width: 100
        name: Metadata
        uid: 52faf640-0a48-474e-b600-224b552bedd6
        userCondition: null
handle: awards
hasTitleField: false
name: Awards
section: 170684cb-0759-412d-8fe9-a4b049a2cb63 # Awards
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
