fieldLayouts:
  adc6d8af-a523-4842-91fd-f873c0d9db0c:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 8991f73e-fc38-46e6-a4db-49b9f6697e67 # Headline
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0d4713d1-5055-456d-b451-5eacbc986e7d # Banner Image
            instructions: null
            label: null
            required: 1
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 55488e76-80a0-494a-8adb-4f6cd00535a8 # Body
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0a2670e7-65b0-45b5-96be-318580462d30 # Featured Awards
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 243afeaf-346c-4b8b-af89-9bd633f855e6 # General Awards
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 2c18936f-5777-4b43-9390-20d3b4f26d51 # Metadata
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Metadata
        sortOrder: 2
handle: awards
hasTitleField: false
name: Awards
section: 170684cb-0759-412d-8fe9-a4b049a2cb63 # Awards
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
