fieldLayouts:
  289ec723-62a2-4b4c-b6d9-d14702ce7039:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 368f02f4-8ba4-41a3-a2c2-d3076b744a95
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dcb31393-3ea4-4a2a-a287-c79dfba31b0a # CTA Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cfa5e35f-992d-445f-b54f-a198af51d719
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0d4713d1-5055-456d-b451-5eacbc986e7d # Banner Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c762b9b6-4bd6-4b7e-92a9-1d6d0285234b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9d60212d-d586-49a1-9525-1f94da3d85f0 # CTA Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c061a77c-ccf9-4852-8d2b-ffa8b99409a1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9432c02d-3660-469e-af4c-461baccc92ce # CTA Footer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d00eb339-08e2-4b86-b50d-c6f3def0c213
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 463765c1-5523-4cda-bad5-85f1dc4e2739
        userCondition: null
handle: ctas
hasTitleField: true
name: 'Call To Actions'
section: 8d55db04-8897-450d-a5f2-625d80a8eab2 # Call To Actions
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
