fieldLayouts:
  df52f150-0a36-49a3-a86d-18638618ac4d:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: b86d426f-3cb1-445d-acc4-27ea2b665ea0 # Hole Number
            instructions: null
            label: null
            required: 1
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0d4713d1-5055-456d-b451-5eacbc986e7d # Banner Image
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 56eab1e4-7cb0-44ee-826e-6fe37e384e72 # Hole Layout Image
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2132d92c-8d1b-447c-9f8d-15b1e166d5f1 # Par
            instructions: null
            label: null
            required: 1
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ef20410f-26b2-4646-9ede-58291bab1f3a # Handicap
            instructions: null
            label: null
            required: 1
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ae4070aa-bea2-4aea-97c5-9e71e2bf31c8 # Hole Description
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7a6e640f-99e8-482a-b081-4155120a1e4b # Caddy Tip
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6a19f290-12c7-40d3-b863-4dfc05650684 # Yardage
            instructions: null
            label: null
            required: 1
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ebccde73-cbc1-4e05-8a10-b7c5afff0f35 # Video
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 2c18936f-5777-4b43-9390-20d3b4f26d51 # Metadata
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Metadata
        sortOrder: 2
handle: general
hasTitleField: true
name: General
section: b604dac5-2242-4481-a8b5-e8302061bbd6 # The Bluffs Hole-By-Hole
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
