fieldLayouts:
  0577a5f2-8ca6-4d1f-8235-3800737b731f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5f5364b0-417b-4fed-a14f-8d940bb333c1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8991f73e-fc38-46e6-a4db-49b9f6697e67 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58da75c4-b64a-4172-a6ae-e9f7eb375216
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0d4713d1-5055-456d-b451-5eacbc986e7d # Banner Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 304c3cce-221d-4fd7-a846-4fc8febdd790
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 55488e76-80a0-494a-8adb-4f6cd00535a8 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c796fff-a375-4de5-95f4-d5d8da3515db
            userCondition: null
            warning: null
            width: 100
        name: Default
        uid: f0c685cc-bd67-4b3b-b890-a9370f223996
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cc80e5df-c1e8-40d1-9935-2b5a608b491a # Sidebar CTAs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bbd51a3f-f758-41cc-9956-b9c457392262
            userCondition: null
            warning: null
            width: 100
        name: Sidebar
        uid: 903957aa-006d-4db4-8429-f779fdf7ff95
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2c18936f-5777-4b43-9390-20d3b4f26d51 # Metadata
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 117ac7cd-8a45-4981-b872-faea2943abd0
            userCondition: null
            warning: null
            width: 100
        name: Metadata
        uid: ecd345a8-52b7-46d3-9d80-80d692513c0d
        userCondition: null
handle: general
hasTitleField: true
name: General
section: cd118c39-5937-4705-b0db-2cb2bb0b7e9b # Courses
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
