fieldLayouts:
  97dba007-c1d1-4c72-beab-c2fbd0578be5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2e50025d-66ee-4599-be37-bdd414970aa9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0d4713d1-5055-456d-b451-5eacbc986e7d # Banner Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4117f265-5012-4fdd-ba66-17ec9090aca8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e1b08e83-a1f1-4c82-9f19-ffa70434df89 # Dining Options
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dfad6283-78b8-4e14-95b0-d9b4da79d2cd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa034695-f302-45c4-818c-842e1842a583 # Gallery
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 015f1c8e-6a52-48d0-9df2-a00c560427c9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5026c7de-ddca-4ea0-97cf-f519b122769b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2c18936f-5777-4b43-9390-20d3b4f26d51 # Metadata
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 729b16d5-14f4-4780-807b-294c1d96a794
            userCondition: null
            warning: null
            width: 100
        name: Metadata
        uid: cf6d6856-a6e5-4293-ba4b-27fa1ee2c695
        userCondition: null
handle: general
hasTitleField: true
name: General
section: f02a0d8f-d625-405c-a782-87b045350b7f # Dining
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
