fieldLayouts:
  2694752c-8d42-493e-86ad-71a8bc1d3e46:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fe56ae6f-33ea-49a5-9645-261d00482aa5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b86d426f-3cb1-445d-acc4-27ea2b665ea0 # Hole Number
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea86c40a-f65f-4e24-9ebf-ee3162fbaf70
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 2132d92c-8d1b-447c-9f8d-15b1e166d5f1 # Par
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7db19a87-61c6-4cf9-b11a-093e408e7b0d
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: ef20410f-26b2-4646-9ede-58291bab1f3a # Handicap
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8cc5a4a3-9884-4ac3-9546-b5767379cb0b
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: da3fdeff-40cf-4697-b57b-9db177a2c7a3
            userCondition: null
          -
            elementCondition: null
            fieldUid: 0d4713d1-5055-456d-b451-5eacbc986e7d # Banner Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 70bb12a9-ba50-41b6-a1e4-2c9e3b81f360
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 56eab1e4-7cb0-44ee-826e-6fe37e384e72 # Hole Layout Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3dedb326-71c6-4779-af66-279a365a64f1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: bd8526fe-6304-46f0-bee8-96850aad229b
            userCondition: null
          -
            elementCondition: null
            fieldUid: ae4070aa-bea2-4aea-97c5-9e71e2bf31c8 # Hole Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5fbe1297-194f-465b-8953-57420bbf3167
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7a6e640f-99e8-482a-b081-4155120a1e4b # Caddy Tip
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 625312fd-2bd8-4654-8395-765b176f441c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6a19f290-12c7-40d3-b863-4dfc05650684 # Yardage
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2be67b48-75d3-419a-967c-81a693ff9874
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ebccde73-cbc1-4e05-8a10-b7c5afff0f35 # Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1958eaf5-aef4-4559-8b8c-f6f0db88905b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 271b0396-281b-4ccf-9b09-69879c71a16c
        userCondition: null
handle: general
hasTitleField: true
name: General
section: 23bb67c9-f116-462a-a1dc-d13ac3f62749 # The Dozen Hole by Hole
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
