fieldLayouts:
  3aa063c9-0938-4ffc-b39a-afbf2250da7b:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 703e4c00-55cf-4b57-a7ee-db4aa2f6e060 # Home Hero
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f9d54a63-f4b4-46a3-9822-b08270fddf91 # Home Courses
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ab98011d-e66d-4a2d-a51b-a20e625f4fca # Home Accommodations
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ea78a6cf-7df9-415d-aa20-2f246a33e383 # Home Dining
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 2c18936f-5777-4b43-9390-20d3b4f26d51 # Metadata
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Metadata
        sortOrder: 2
handle: homepage
hasTitleField: true
name: Homepage
section: b7b6f2fe-0047-4f19-86c9-07f96a339ebb # Homepage
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
