fieldLayouts:
  7825e274-3c43-48a9-9433-d9d0ed3b31a0:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 8991f73e-fc38-46e6-a4db-49b9f6697e67 # Headline
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0d4713d1-5055-456d-b451-5eacbc986e7d # Banner Image
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 58d379a7-f464-4baf-8555-e5b71c12d289 # Intro Block
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1f3294c6-b9a7-46b9-aaf4-70bcf8b46237 # Accommodation Buckets
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5fd92c59-65ac-442f-883a-e5d8d867ed86 # Content Block
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: ab4827b9-4344-4f89-8d9f-435cdb4c0699 # Accommodation Form Headline
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0ef55052-1ae5-436b-b9cd-64be16fcf0db # Accommodation Form Content
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3ec5a707-06b4-47ff-9a7d-eec3255596fe # Accommodation Form
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Form
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 0e2a9e40-9910-47e0-b2d7-052c425013b2 # Accommodation Extras
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Extras
        sortOrder: 3
      -
        elements:
          -
            fieldUid: 2c18936f-5777-4b43-9390-20d3b4f26d51 # Metadata
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Metadata
        sortOrder: 4
handle: landing
hasTitleField: true
name: Landing
section: 0c9fc74f-f5c7-4b5f-8b80-8ea98aa0999e # Accommodations
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
