fieldLayouts:
  7825e274-3c43-48a9-9433-d9d0ed3b31a0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 374855e2-a6a3-4dd0-9f2c-6e921dd2c3d1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8991f73e-fc38-46e6-a4db-49b9f6697e67 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 594b3fa4-21c1-4cbc-b123-f2b7a74fbb93
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2710ce99-0681-4cfb-bffb-2d1cbb375c57 # Simple Banner
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 540d2e65-6d28-4b64-901a-a22ba40aed3d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 2710ce99-0681-4cfb-bffb-2d1cbb375c57 # Simple Banner
                  uid: 83a3074a-a7c4-43fe-b4d7-27c257e25887
                  value: false
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: f19fa97c-7a36-4123-bc74-ed3e6b4f2c29 # Hero Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f471c1b-c2a1-4d05-a65a-e9a1d0749222
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 2710ce99-0681-4cfb-bffb-2d1cbb375c57 # Simple Banner
                  uid: e54eca18-f3f9-4b58-9a28-24da26288c7d
                  value: false
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: b9701f69-ede3-4a6c-b7b7-baa1856327ec # Banner Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f3730639-62b4-4823-bf00-a9f6f529e5fa
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 2710ce99-0681-4cfb-bffb-2d1cbb375c57 # Simple Banner
                  uid: f0c97ab4-7026-4175-ac35-ac2e9816286b
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 0d4713d1-5055-456d-b451-5eacbc986e7d # Banner Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a108b2b8-24b6-4c5c-bc20-958be99137e6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1f3294c6-b9a7-46b9-aaf4-70bcf8b46237 # Accommodation Buckets
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a3ac170-0474-4738-a892-a287e9b14dc9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5fd92c59-65ac-442f-883a-e5d8d867ed86 # Content Block
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 074c5409-efe6-4547-a80e-abb9797d8759
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f8f2f03e-0c0f-42b5-9c26-55fa779fc89e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ab4827b9-4344-4f89-8d9f-435cdb4c0699 # Accommodation Form Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb638e92-0f3f-4def-b637-ea40b9d163f6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0ef55052-1ae5-436b-b9cd-64be16fcf0db # Accommodation Form Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 359ea22f-a9aa-4371-a70e-d64ca85ffd83
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3ec5a707-06b4-47ff-9a7d-eec3255596fe # Accommodation Form
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 04ef569f-9d8e-4c0c-bbcb-342055eff26e
            userCondition: null
            warning: null
            width: 100
        name: Form
        uid: a9120d75-79ab-4291-8aa9-9903b2ca85e2
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0e2a9e40-9910-47e0-b2d7-052c425013b2 # Accommodation Extras
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5db68bf3-d429-464c-9a36-fd813b8abcd8
            userCondition: null
            warning: null
            width: 100
        name: Extras
        uid: 3bc3c370-2b25-4738-b88b-382cd2d62aaf
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2c18936f-5777-4b43-9390-20d3b4f26d51 # Metadata
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf7cc58b-8208-4d4a-9c80-cdb0db109d33
            userCondition: null
            warning: null
            width: 100
        name: Metadata
        uid: 655dbfc8-3384-4c4d-967f-d5c479a2107f
        userCondition: null
handle: landing
hasTitleField: true
name: Landing
section: 0c9fc74f-f5c7-4b5f-8b80-8ea98aa0999e # Accommodations
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
