fieldLayouts:
  b913aff2-9061-46e4-aab9-f6f8b998c83c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7db88019-9795-48d4-906b-b1dbcd507aed
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8991f73e-fc38-46e6-a4db-49b9f6697e67 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a9a3eb28-2524-4a2e-9845-d7f9683c04d3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0d4713d1-5055-456d-b451-5eacbc986e7d # Banner Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a23a1fd1-db3c-4829-848b-d0615850a7eb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 716abbda-6a26-45cc-b52c-901463010380 # Page Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26f9d038-3d46-43f1-b84d-767986974868
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0e2a9e40-9910-47e0-b2d7-052c425013b2 # Accommodation Extras
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ebe1cf18-ed07-4745-8b86-7a6cd4d3bfc1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 534889af-aaf6-4919-b059-6b1ec452a6a4
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2c18936f-5777-4b43-9390-20d3b4f26d51 # Metadata
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5d27c72-891b-4094-90fe-39b27748272f
            userCondition: null
            warning: null
            width: 100
        name: Metadata
        uid: ca6324fb-069b-4390-9c76-01f2dc221a1d
        userCondition: null
handle: landing
hasTitleField: true
name: Landing
section: f02a0d8f-d625-405c-a782-87b045350b7f # Dining
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
