fieldLayouts:
  ee7a2d78-6be6-4d76-8448-8b57a35f8207:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7bb58bed-1433-430a-837e-ed41c8001532
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a22ed9d6-243d-484b-add7-97a6dd764551 # Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98204ff3-8d12-4465-83df-7aeef0fbe420
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 55488e76-80a0-494a-8adb-4f6cd00535a8 # Body
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3c3a81b-2f4c-4796-9998-190e439c3b2b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0339d640-3170-4fbe-b05e-bc617f16c7c3 # Tags
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1b3a51c-1695-421b-9d7c-21d9d2dcf2d8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3e573000-e0c7-4b8b-a2fc-9d330c28cdbb
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cc80e5df-c1e8-40d1-9935-2b5a608b491a # Sidebar CTAs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a6f9db0-c938-4a15-914a-59274bac53b8
            userCondition: null
            warning: null
            width: 100
        name: Sidebar
        uid: d91cb920-e808-40b9-9b58-f54620965035
        userCondition: null
handle: news
hasTitleField: true
name: News
section: 19d04551-214f-4e9b-9a5e-ff66d6fe1028 # News
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
