fieldLayouts:
  17b9e017-0095-4de2-b34a-1d6125e6c394:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 06c8800a-8f6f-4ed0-b9ae-790439609960
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8991f73e-fc38-46e6-a4db-49b9f6697e67 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47bd864b-9238-4b8e-82c7-50db29444280
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0d4713d1-5055-456d-b451-5eacbc986e7d # Banner Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d32c948-71a1-4542-a195-97060b6d21d1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 55488e76-80a0-494a-8adb-4f6cd00535a8 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86b416cc-ce77-4db8-9d06-e2a8e2f2d4c0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 777c02dc-bca5-4517-8d40-5156270131fa # Form
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0a128ea-3eb9-4963-9a6b-67804dbc7948
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0f38f0fd-b96e-45a1-aaf8-c41615ef2713
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cc80e5df-c1e8-40d1-9935-2b5a608b491a # Sidebar CTAs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c22da61e-4a95-4586-9b75-706c5ed98a67
            userCondition: null
            warning: null
            width: 100
        name: Sidebar
        uid: 39e809ce-d260-4105-a042-941f39699d90
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2c18936f-5777-4b43-9390-20d3b4f26d51 # Metadata
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7b1e444-3e03-43cb-91f7-ebfa4d9db1f6
            userCondition: null
            warning: null
            width: 100
        name: Metadata
        uid: 66f4f829-f1ad-46e3-a1a3-970d6d0d3e83
        userCondition: null
handle: pages
hasTitleField: true
name: Pages
section: 3dfade29-0d50-45dd-9bf0-0b0a2fed7406 # Utility Pages
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
