defaultPlacement: end
fieldLayouts:
  648ebd31-7b50-451c-9eda-9b0e01d9f71e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 8b42a22c-a41b-42c9-a31c-fabaeab5ed55
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 77435ef2-06c1-48db-b6a3-e186b58124fd
        userCondition: null
handle: news
name: News
siteSettings:
  076725fd-bc7e-48fa-88ce-2d58cbee2749: # Arcadia Bluffs (en-US)
    hasUrls: true
    template: news/_category
    uriFormat: '{% if object.level == 1 %}news/{slug}{% else %}{parent.uri}/{slug}{% endif %}'
structure:
  maxLevels: null
  uid: ee62ce4c-5796-48b4-9d15-24e069c88bc3
