baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: en_us
hasUrls: true
language: en-US
name: 'Arcadia Bluffs (en-US)'
primary: true
siteGroup: 855df4ea-2594-4a30-98f0-07f4302d7037 # Arcadia Bluffs (en-US)
sortOrder: 1
