childBlocks: null
conditions: null
description: ''
enabled: true
field: 0e2a9e40-9910-47e0-b2d7-052c425013b2 # Accommodation Extras
fieldLayouts:
  d6f7830d-d889-4bf0-8918-b02cbb7f5414:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0e38621c-2421-4292-ae5b-aa86828ee673 # Linked List
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93cc887f-b18b-4594-b818-3ba6c707933d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: eeecde73-e3d4-472f-b004-9012a69c0d84
        userCondition: null
group: null
groupChildBlockTypes: true
handle: column
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Column
topLevel: true
