childBlocks: null
conditions: null
description: ''
enabled: true
field: 47797459-7179-441b-8d49-e58016d12cb1 # Executive Team
fieldLayouts:
  009af992-5c2d-4c2d-9184-33e53fda9249:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b67c258a-ab57-4bce-8a04-dd8aa2b891dd # Executive Team Row
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d278a399-a760-4d48-80d1-b1f7503cfa81
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9b046874-f2b2-40c3-94e2-5af3dde991b4
        userCondition: null
group: null
groupChildBlockTypes: true
handle: teamRow
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Team Row'
topLevel: true
