fieldLayouts:
  45a84583-7747-4b4f-8a35-e7b33a70c55a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: f4ac3d9f-8ff5-4162-a397-84b5b9539318
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1c338088-3bef-4c85-bea2-e47e21536196
        userCondition: null
fs: metadata
handle: metadata
name: Metadata
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
