fieldLayouts:
  ce3a6341-432e-4438-9e84-b867623b1511:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: userPhotos
hasUrls: false
name: 'User Photos'
settings:
  path: userphotos
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: null
type: craft\volumes\Local
url: ''
