fieldLayouts:
  ce3a6341-432e-4438-9e84-b867623b1511:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 51b9e799-6246-4c5b-a502-0f1defbe23d8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 48598d69-105c-49e0-a256-f957fdd42084
        userCondition: null
fs: userPhotos
handle: userPhotos
name: 'User Photos'
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
