columnSuffix: null
contentColumnType: text
fieldGroup: 2eac97af-c8bb-4f52-82d5-7b98c2c2bb90 # Accommodations
handle: accommodationLink
instructions: ''
name: 'Accommodation Link'
searchable: true
settings:
  allowCustomText: '1'
  allowTarget: '1'
  defaultText: ''
  selectLinkText: ''
  types:
    __assoc__:
      -
        - presseddigital\linkit\models\Url
        -
          __assoc__:
            -
              - enabled
              - 1
      -
        - presseddigital\linkit\models\Entry
        -
          __assoc__:
            0:
              - enabled
              - 1
            2:
              - sources
              - '*'
            3:
              - customSelectionLabel
              - 'Select an entry'
translationKeyFormat: null
translationMethod: none
type: presseddigital\linkit\fields\LinkitField
