columnSuffix: null
contentColumnType: string
fieldGroup: 2eac97af-c8bb-4f52-82d5-7b98c2c2bb90 # Accommodations
handle: accommodationBuckets
instructions: null
name: 'Accommodation Buckets'
searchable: true
settings:
  contentTable: '{{%matrixcontent_accommodationbuckets}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
