contentColumnType: string
fieldGroup: 0cf694de-6970-4003-8a9d-984c9ba91d3f # Course Landing
handle: bannerLink
instructions: ''
name: 'Banner Link'
searchable: true
settings:
  allowCustomText: '1'
  allowTarget: '1'
  defaultText: ''
  selectLinkText: ''
  types:
    presseddigital\linkit\models\Entry:
      customLabel: null
      customSelectionLabel: 'Select an entry'
      enabled: 1
      sources: '*'
    presseddigital\linkit\models\Url:
      customLabel: null
      enabled: 1
translationKeyFormat: null
translationMethod: none
type: presseddigital\linkit\fields\LinkitField
