columnSuffix: null
contentColumnType: string
fieldGroup: 2de0d27e-44cc-4a0b-b5b3-4e9537340946 # Default
handle: bannerImage
instructions: 'Full-screen, featured image for the page. If no image is selected, a default image will be displayed. '
name: 'Banner Image'
searchable: true
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Add a Banner Image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
