columnSuffix: null
contentColumnType: text
fieldGroup: 0cf694de-6970-4003-8a9d-984c9ba91d3f # Course Landing
handle: bannerLink
instructions: ''
name: 'Banner Link'
searchable: true
settings:
  allowCustomText: '1'
  allowTarget: '1'
  defaultText: ''
  selectLinkText: ''
  types:
    __assoc__:
      -
        - presseddigital\linkit\models\Url
        -
          __assoc__:
            -
              - enabled
              - 1
      -
        - presseddigital\linkit\models\Entry
        -
          __assoc__:
            0:
              - enabled
              - 1
            2:
              - sources
              - '*'
            3:
              - customSelectionLabel
              - 'Select an entry'
translationKeyFormat: null
translationMethod: none
type: presseddigital\linkit\fields\LinkitField
