columnSuffix: null
contentColumnType: text
fieldGroup: aeecde4f-2032-46b1-968b-ad04618e7172 # Menu
handle: class
instructions: ''
name: Class
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
