columnSuffix: null
contentColumnType: string
fieldGroup: 2de0d27e-44cc-4a0b-b5b3-4e9537340946 # Default
handle: contentBlock
instructions: ''
name: 'Content Block'
searchable: true
settings:
  contentTable: '{{%matrixcontent_contentblock}}'
  maxBlocks: '1'
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
