columnSuffix: null
contentColumnType: string
fieldGroup: 0cf694de-6970-4003-8a9d-984c9ba91d3f # Course Landing
handle: courseHistory
instructions: null
name: 'Course History'
searchable: true
settings:
  contentTable: '{{%matrixcontent_coursehistory}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
