columnSuffix: null
contentColumnType: text
fieldGroup: 2de0d27e-44cc-4a0b-b5b3-4e9537340946 # Default
handle: ctaBody
instructions: ''
name: 'CTA Body'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 49a3924a-193d-40e7-ac57-4709787234ed # Simple
  columnType: text
  defaultTransform: ''
  enableSourceEditingForNonAdmins: true
  purifierConfig: ''
  purifyHtml: '1'
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
