columnSuffix: null
contentColumnType: string
fieldGroup: 2de0d27e-44cc-4a0b-b5b3-4e9537340946 # Default
handle: ctaFooter
instructions: null
name: 'CTA Footer'
searchable: true
settings:
  contentTable: '{{%matrixcontent_ctafooter}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
