columnSuffix: null
contentColumnType: text
fieldGroup: 2de0d27e-44cc-4a0b-b5b3-4e9537340946 # Default
handle: ctaHeadline
instructions: null
name: 'CTA Headline'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
