columnSuffix: null
contentColumnType: string
fieldGroup: 2eac97af-c8bb-4f52-82d5-7b98c2c2bb90 # Accommodations
handle: ctaNew
instructions: ''
name: CTA
searchable: true
settings:
  columns:
    224:
      __assoc__:
        -
          - width
          - ''
    225:
      __assoc__:
        -
          - width
          - ''
    226:
      __assoc__:
        -
          - width
          - ''
  contentTable: null
  fieldLayout: row
  maxRows: null
  minRows: null
  placeholderKey: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: 'Add a row'
  staticField: '1'
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
