columnSuffix: null
contentColumnType: string
fieldGroup: 441642ef-65bb-460b-bf11-9a7b5014942b # Contact
handle: executiveTeam
instructions: ''
name: 'Executive Team'
searchable: true
settings:
  maxBlocks: null
  maxLevels: null
  maxTopBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
  wasModified: false
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
