columnSuffix: null
contentColumnType: text
fieldGroup: 441642ef-65bb-460b-bf11-9a7b5014942b # Contact
handle: executiveTeamHeadline
instructions: null
name: 'Executive Team Headline'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
