columnSuffix: null
contentColumnType: string
fieldGroup: 16ea3636-5874-40e9-aa29-e602ce41ffcf # Navigation
handle: footerMenu
instructions: ''
name: 'Footer Menu'
searchable: false
settings:
  contentTable: '{{%stc_footermenu}}'
  fieldLayout: row
  maxRows: '10'
  minRows: ''
  placeholderKey: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: 'Add a Link'
  staticField: ''
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
