columnSuffix: null
contentColumnType: string
fieldGroup: 2de0d27e-44cc-4a0b-b5b3-4e9537340946 # Default
handle: gallery
instructions: ''
name: Gallery
searchable: true
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
  defaultUploadLocationSubpath: ''
  limit: '15'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Add an Image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  singleUploadLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
