columnSuffix: null
contentColumnType: text
fieldGroup: 6ad5585d-72c6-4d83-a4f8-c364ef010008 # Gift Cards
handle: giftCardsIntroduction
instructions: ''
name: 'Gift Cards Introduction'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: '1'
  redactorConfig: ''
  removeEmptyTags: true
  removeInlineStyles: true
  removeNbsp: true
  showHtmlButtonForNonAdmins: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
