columnSuffix: null
contentColumnType: text
fieldGroup: 106e43e9-e710-4ddd-9c6d-ed1df333503c # Hole By Hole
handle: holeDescription
instructions: ''
name: 'Hole Description'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: '1'
  redactorConfig: ''
  removeEmptyTags: true
  removeInlineStyles: true
  removeNbsp: true
  showHtmlButtonForNonAdmins: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
