columnSuffix: null
contentColumnType: string
fieldGroup: 267e048a-991b-4411-a5f9-82512829882d # Home
handle: homeDining
instructions: null
name: 'Home Dining'
searchable: true
settings:
  blockTypeFields: 0
  changedFieldIndicator: null
  columns:
    __assoc__:
      -
        - 49b14ddc-b863-47cf-9f09-87654c5b6f65 # Headline
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 8f38cf3e-638f-4bad-aff2-ecc59c8c6303 # Text
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 95930b1a-46ab-472b-bbc8-08004eee0333 # Link
        -
          __assoc__:
            -
              - width
              - ''
      -
        - bbfb2374-a525-4465-984d-d47c476db769 # Dining Options
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_homedining}}'
  fieldLayout: row
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: 'Add a row'
  staticField: true
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
