columnSuffix: null
contentColumnType: string
fieldGroup: 267e048a-991b-4411-a5f9-82512829882d # Home
handle: homeHero
instructions: null
name: 'Home Hero'
searchable: true
settings:
  blockTypeFields: 0
  changedFieldIndicator: 978889675
  columns:
    __assoc__:
      -
        - d9cb1d6c-2477-4fd3-8b36-6d7a1a3161f0 # Headline
        -
          __assoc__:
            -
              - width
              - ''
      -
        - ea8304eb-f854-4dc5-b1df-84fbb8c51ea7 # Button
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_homehero}}'
  fieldLayout: row
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: 'Add a row'
  staticField: true
translationKeyFormat: null
translationMethod: none
type: verbb\supertable\fields\SuperTableField
