columnSuffix: null
contentColumnType: string
fieldGroup: 2de0d27e-44cc-4a0b-b5b3-4e9537340946 # Default
handle: linkedList
instructions: null
name: 'Linked List'
searchable: true
settings:
  contentTable: '{{%matrixcontent_linkedlist}}'
  maxBlocks: 3
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
