columnSuffix: null
contentColumnType: string
fieldGroup: 441642ef-65bb-460b-bf11-9a7b5014942b # Contact
handle: localAirports
instructions: null
name: 'Local Airports'
searchable: true
settings:
  contentTable: '{{%matrixcontent_localairports}}'
  maxBlocks: 3
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
