columnSuffix: null
contentColumnType: string
fieldGroup: 16ea3636-5874-40e9-aa29-e602ce41ffcf # Navigation
handle: mainNavigation
instructions: ''
name: 'Main Navigation'
searchable: false
settings:
  contentTable: '{{%stc_mainnavigation}}'
  fieldLayout: row
  maxRows: '8'
  minRows: ''
  placeholderKey: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: 'Add a Link'
  staticField: ''
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
