columnSuffix: null
contentColumnType: text
fieldGroup: 11950123-d1fd-4f74-b0cd-016b75c75cb9 # Metadata
handle: metadata
instructions: null
name: Metadata
searchable: true
settings:
  elementDisplayPreviewType: google
  facebookEnabledFields:
    - seoPreview
    - ogType
    - ogTitle
    - ogSiteNamePosition
    - ogDescription
    - ogImage
    - ogImageTransform
    - ogImageTransformMode
    - ogImageDescription
  facebookTabEnabled: '1'
  generalEnabledFields:
    - seoPreview
    - mainEntityOfPage
    - seoTitle
    - siteNamePosition
    - seoDescription
    - seoKeywords
    - seoImage
    - seoImageTransform
    - seoImageTransformMode
    - seoImageDescription
  generalTabEnabled: '1'
  sitemapEnabledFields:
    - sitemapUrls
    - sitemapAssets
    - sitemapAssetTransform
    - sitemapFiles
    - sitemapAltLinks
    - sitemapChangeFreq
    - sitemapPriority
    - sitemapLimit
  sitemapTabEnabled: '1'
  twitterEnabledFields:
    - seoPreview
    - twitterCardType
    - twitterCreator
    - twitterTitle
    - twitterSiteNamePosition
    - twitterDescription
    - twitterImage
    - transformTwitterImage
    - twitterImageTransformMode
    - twitterImageDescription
  twitterTabEnabled: '1'
translationKeyFormat: null
translationMethod: none
type: nystudio107\seomatic\fields\SeoSettings
