columnSuffix: null
contentColumnType: string
fieldGroup: aeecde4f-2032-46b1-968b-ad04618e7172 # Menu
handle: openInNewTab
instructions: null
name: 'Open in New Tab?'
searchable: true
settings:
  columnType: string
  options:
    -
      __assoc__:
        -
          - label
          - 'No'
        -
          - value
          - 'false'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Yes'
        -
          - value
          - 'true'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
