columnSuffix: null
contentColumnType: text
fieldGroup: 2de0d27e-44cc-4a0b-b5b3-4e9537340946 # Default
handle: overview
instructions: ''
name: Overview
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 4dc3cdd6-aaf2-421a-bd6c-aaa6de96e874 # Default
  columnType: text
  defaultTransform: ''
  enableSourceEditingForNonAdmins: true
  purifierConfig: null
  purifyHtml: '1'
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
