columnSuffix: null
contentColumnType: string
fieldGroup: a6c2ddd7-0756-4257-a628-2d1917856bb6 # Dining
handle: pageLinks
instructions: ''
name: 'Page Links'
searchable: true
settings:
  contentTable: '{{%matrixcontent_pagelinks}}'
  maxBlocks: '3'
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
