columnSuffix: null
contentColumnType: text
fieldGroup: 106e43e9-e710-4ddd-9c6d-ed1df333503c # Hole By Hole
handle: par
instructions: null
name: Par
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
