columnSuffix: null
contentColumnType: string
fieldGroup: f166e127-51d5-4ea5-9f69-0e3973d61913 # Rates
handle: ratesList
instructions: null
name: 'Rates List'
searchable: true
settings:
  contentTable: '{{%matrixcontent_rateslist}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
