columnSuffix: null
contentColumnType: string
fieldGroup: aeecde4f-2032-46b1-968b-ad04618e7172 # Menu
handle: relatedEntry
instructions: 'Select an existing entry in our sitemap'
name: 'Related Entry'
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add an Entry'
  showSiteMenu: true
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
