columnSuffix: null
contentColumnType: text
fieldGroup: 0cf694de-6970-4003-8a9d-984c9ba91d3f # Course Landing
handle: scorecard
instructions: "color options:\r\nblack. blue, white, gold, red, gray (leave blank for default)"
name: Scorecard
searchable: true
settings:
  addRowLabel: 'Add a row'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Label
            -
              - handle
              - label
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - '1'
            -
              - handle
              - one
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col3
        -
          __assoc__:
            -
              - heading
              - '2'
            -
              - handle
              - two
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col4
        -
          __assoc__:
            -
              - heading
              - '3'
            -
              - handle
              - three
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col5
        -
          __assoc__:
            -
              - heading
              - '4'
            -
              - handle
              - four
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col6
        -
          __assoc__:
            -
              - heading
              - '5'
            -
              - handle
              - five
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col7
        -
          __assoc__:
            -
              - heading
              - '6'
            -
              - handle
              - six
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col8
        -
          __assoc__:
            -
              - heading
              - '7'
            -
              - handle
              - seven
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col9
        -
          __assoc__:
            -
              - heading
              - '8'
            -
              - handle
              - eight
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col10
        -
          __assoc__:
            -
              - heading
              - '9'
            -
              - handle
              - nine
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col11
        -
          __assoc__:
            -
              - heading
              - Out
            -
              - handle
              - out
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col12
        -
          __assoc__:
            -
              - heading
              - '10'
            -
              - handle
              - ten
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col13
        -
          __assoc__:
            -
              - heading
              - '11'
            -
              - handle
              - eleven
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col14
        -
          __assoc__:
            -
              - heading
              - '12'
            -
              - handle
              - twelve
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col15
        -
          __assoc__:
            -
              - heading
              - '13'
            -
              - handle
              - thirteen
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col16
        -
          __assoc__:
            -
              - heading
              - '14'
            -
              - handle
              - fourteen
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col17
        -
          __assoc__:
            -
              - heading
              - '15'
            -
              - handle
              - fifteen
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col18
        -
          __assoc__:
            -
              - heading
              - '16'
            -
              - handle
              - sixteen
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col19
        -
          __assoc__:
            -
              - heading
              - '17'
            -
              - handle
              - seventeen
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col20
        -
          __assoc__:
            -
              - heading
              - '18'
            -
              - handle
              - eighteen
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col21
        -
          __assoc__:
            -
              - heading
              - IN
            -
              - handle
              - in
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col22
        -
          __assoc__:
            -
              - heading
              - TOT
            -
              - handle
              - total
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col23
        -
          __assoc__:
            -
              - heading
              - Color
            -
              - handle
              - color
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - col2
          - ''
        -
          - col3
          - ''
        -
          - col4
          - ''
        -
          - col5
          - ''
        -
          - col6
          - ''
        -
          - col7
          - ''
        -
          - col8
          - ''
        -
          - col9
          - ''
        -
          - col10
          - ''
        -
          - col11
          - ''
        -
          - col12
          - ''
        -
          - col13
          - ''
        -
          - col14
          - ''
        -
          - col15
          - ''
        -
          - col16
          - ''
        -
          - col17
          - ''
        -
          - col18
          - ''
        -
          - col19
          - ''
        -
          - col20
          - ''
        -
          - col21
          - ''
        -
          - col22
          - ''
        -
          - col23
          - ''
  maxRows: null
  minRows: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
