columnSuffix: null
contentColumnType: string
fieldGroup: 0cf694de-6970-4003-8a9d-984c9ba91d3f # Course Landing
handle: slopeTables
instructions: null
name: 'Slope Tables'
searchable: true
settings:
  contentTable: '{{%matrixcontent_slopetables}}'
  maxBlocks: 2
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
