columnSuffix: null
contentColumnType: text
fieldGroup: 27878486-148f-45b2-8d48-2a355ca5370b # Globals
handle: subscribeHeadline
instructions: ''
name: 'Subscribe Headline'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
