columnSuffix: null
contentColumnType: string
fieldGroup: 2de0d27e-44cc-4a0b-b5b3-4e9537340946 # Default
handle: tags
instructions: null
name: Tags
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: true
  source: 'taggroup:e3dd14d9-3105-4555-b8c3-9b7328d545ec' # Default
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Tags
