columnSuffix: null
contentColumnType: text
fieldGroup: 6ad5585d-72c6-4d83-a4f8-c364ef010008 # Gift Cards
handle: thankYouMessage
instructions: null
name: 'Thank You Message'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  characterLimit: null
  ckeConfig: 4dc3cdd6-aaf2-421a-bd6c-aaa6de96e874 # Default
  columnType: text
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  showWordCount: false
  sourceEditingGroups: '*'
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
