field: fd52f2bc-9e8e-4025-9502-fab5a89e68ae # Arcadia Bluffs Address
fieldLayouts:
  3bf83eeb-a959-4cbe-8470-88a96fd628b9:
    tabs:
      -
        elements:
          -
            fieldUid: aae837ba-06f9-4343-b212-2889073937b0 # Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fc68f54b-60ab-4251-8ec9-15ea9b776eef # Street Address 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cbae5fec-e67e-4c89-b03f-a329eefefcda # Street Address 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5554e38f-dda8-4910-8ef4-8c4b7e1a63ee # City
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 928a4a05-b9d0-4bbe-aefb-6ca1bb44af92 # State
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0c6882d0-e994-4811-afea-7c1c2d619d97 # Postal Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d1b93d4f-3a60-41aa-ab26-b13840fa86e0 # Country
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0c6882d0-e994-4811-afea-7c1c2d619d97: # Postal Code
    columnSuffix: soalzyst
    contentColumnType: text
    fieldGroup: null
    handle: postalCode
    instructions: ''
    name: 'Postal Code'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  928a4a05-b9d0-4bbe-aefb-6ca1bb44af92: # State
    columnSuffix: ysltweim
    contentColumnType: text
    fieldGroup: null
    handle: state
    instructions: ''
    name: State
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  5554e38f-dda8-4910-8ef4-8c4b7e1a63ee: # City
    columnSuffix: eqhypzjj
    contentColumnType: text
    fieldGroup: null
    handle: city
    instructions: ''
    name: City
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  aae837ba-06f9-4343-b212-2889073937b0: # Name
    columnSuffix: tnkgrlsg
    contentColumnType: text
    fieldGroup: null
    handle: addressName
    instructions: ''
    name: Name
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cbae5fec-e67e-4c89-b03f-a329eefefcda: # Street Address 2
    columnSuffix: nvhvyyww
    contentColumnType: text
    fieldGroup: null
    handle: streetAddress2
    instructions: ''
    name: 'Street Address 2'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d1b93d4f-3a60-41aa-ab26-b13840fa86e0: # Country
    columnSuffix: vjcvzhot
    contentColumnType: text
    fieldGroup: null
    handle: country
    instructions: ''
    name: Country
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  fc68f54b-60ab-4251-8ec9-15ea9b776eef: # Street Address 1
    columnSuffix: dcbzztrx
    contentColumnType: text
    fieldGroup: null
    handle: streetAddress1
    instructions: ''
    name: 'Street Address 1'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
