changedFieldIndicator: null
field: ea78a6cf-7df9-415d-aa20-2f246a33e383 # Home Dining
fieldLayouts:
  547e8b78-82de-4c1e-8f0c-02a503b827cb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 49b14ddc-b863-47cf-9f09-87654c5b6f65 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e25dfb2c-95b6-4cbc-b125-c692de8b95ac
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8f38cf3e-638f-4bad-aff2-ecc59c8c6303 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 610e81ba-1d61-4412-bf5e-c0ebfbe6e1d4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 95930b1a-46ab-472b-bbc8-08004eee0333 # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 78753744-a34e-4b07-93fa-6d9cd523050d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bbfb2374-a525-4465-984d-d47c476db769 # Dining Options
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 386f1016-f233-4e10-a9f0-fa77887b2a17
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 302ead6f-69cb-4d01-8cac-97d3470b17bb
        userCondition: null
fields:
  8f38cf3e-638f-4bad-aff2-ecc59c8c6303: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      characterLimit: null
      ckeConfig: 4dc3cdd6-aaf2-421a-bd6c-aaa6de96e874 # Default
      columnType: text
      defaultTransform: null
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      showWordCount: false
      sourceEditingGroups: '*'
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  49b14ddc-b863-47cf-9f09-87654c5b6f65: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  95930b1a-46ab-472b-bbc8-08004eee0333: # Link
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: linkData
    instructions: null
    name: Link
    searchable: true
    settings:
      allowCustomText: true
      allowTarget: true
      defaultText: null
      selectLinkText: ''
      types:
        __assoc__:
          -
            - presseddigital\linkit\models\Email
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Phone
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Url
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
                -
                  - allowAlias
                  - '1'
                -
                  - allowMailto
                  - '1'
                -
                  - allowHash
                  - '1'
                -
                  - allowPaths
                  - '1'
          -
            - presseddigital\linkit\models\Twitter
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Facebook
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Instagram
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\LinkedIn
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Entry
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  -
                    - 'section:0c9fc74f-f5c7-4b5f-8b80-8ea98aa0999e' # Accommodations
                    - 'section:cd118c39-5937-4705-b0db-2cb2bb0b7e9b' # Courses
                    - 'section:f02a0d8f-d625-405c-a782-87b045350b7f' # Dining
                    - 'section:19d04551-214f-4e9b-9a5e-ff66d6fe1028' # News
                    - singles
                    - 'section:3dfade29-0d50-45dd-9bf0-0b0a2fed7406' # Utility Pages
                -
                  - customSelectionLabel
                  - 'Select an entry'
          -
            - presseddigital\linkit\models\Category
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - ''
          -
            - presseddigital\linkit\models\Asset
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - ''
          -
            - presseddigital\linkit\models\User
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - ''
                -
                  - userPath
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: presseddigital\linkit\fields\LinkitField
  bbfb2374-a525-4465-984d-d47c476db769: # Dining Options
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: diningOptions
    instructions: null
    name: 'Dining Options'
    searchable: true
    settings:
      contentTable: '{{%matrixcontent_diningoptions_1}}'
      maxBlocks: 3
      minBlocks: null
      propagationKeyFormat: null
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
