changedFieldIndicator: null
field: f9d54a63-f4b4-46a3-9822-b08270fddf91 # Home Courses
fieldLayouts:
  ab4014ad-b5a0-4aa2-af71-a786704e6584:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6cbfc500-609a-481a-b793-29875ee605b0 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 052a6b05-66ba-4859-b72f-73bc86a29429
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2e0e521e-50dc-4fc4-b923-0360760a0c28 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27178228-c2d1-4857-a98b-1d56952c3112
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4df910d9-30d4-4eac-8b59-435d3143c244 # Video Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 66177d56-85e5-40e5-923f-e10d38dea9dc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 330eac69-3318-422a-861b-d841fff06fef # Video Subheadline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 292a871e-c297-4ea2-93d0-939704526790
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 96026f6b-4401-4546-b7e2-9549a9ecbf38 # Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23dfa12e-6ccc-474e-b0f3-918f8622381d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: df2fb927-6c87-4678-9950-d3a004411ca8 # Courses
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2e155712-4137-4e45-a641-98e6d69806bb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 695debb0-b140-4373-9b0b-fe6d5972e872
        userCondition: null
fields:
  2e0e521e-50dc-4fc4-b923-0360760a0c28: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      characterLimit: null
      ckeConfig: 4dc3cdd6-aaf2-421a-bd6c-aaa6de96e874 # Default
      columnType: text
      defaultTransform: null
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      showWordCount: false
      sourceEditingGroups: '*'
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  4df910d9-30d4-4eac-8b59-435d3143c244: # Video Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: videoHeadline
    instructions: null
    name: 'Video Headline'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  6cbfc500-609a-481a-b793-29875ee605b0: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  330eac69-3318-422a-861b-d841fff06fef: # Video Subheadline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: videoSubheadline
    instructions: null
    name: 'Video Subheadline'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  96026f6b-4401-4546-b7e2-9549a9ecbf38: # Video
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: video
    instructions: null
    name: Video
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 2
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  df2fb927-6c87-4678-9950-d3a004411ca8: # Courses
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: courses
    instructions: null
    name: Courses
    searchable: true
    settings:
      contentTable: '{{%matrixcontent_courses}}'
      maxBlocks: 3
      minBlocks: null
      propagationKeyFormat: null
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
