field: f9d54a63-f4b4-46a3-9822-b08270fddf91 # Home Courses
fieldLayouts:
  ab4014ad-b5a0-4aa2-af71-a786704e6584:
    tabs:
      -
        elements:
          -
            fieldUid: 6cbfc500-609a-481a-b793-29875ee605b0 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2e0e521e-50dc-4fc4-b923-0360760a0c28 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4df910d9-30d4-4eac-8b59-435d3143c244 # Video Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 330eac69-3318-422a-861b-d841fff06fef # Video Subheadline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 96026f6b-4401-4546-b7e2-9549a9ecbf38 # Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: df2fb927-6c87-4678-9950-d3a004411ca8 # Courses
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2e0e521e-50dc-4fc4-b923-0360760a0c28: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  4df910d9-30d4-4eac-8b59-435d3143c244: # Video Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: videoHeadline
    instructions: ''
    name: 'Video Headline'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  6cbfc500-609a-481a-b793-29875ee605b0: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  330eac69-3318-422a-861b-d841fff06fef: # Video Subheadline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: videoSubheadline
    instructions: ''
    name: 'Video Subheadline'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  96026f6b-4401-4546-b7e2-9549a9ecbf38: # Video
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: video
    instructions: ''
    name: Video
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '2'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  df2fb927-6c87-4678-9950-d3a004411ca8: # Courses
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: courses
    instructions: ''
    name: Courses
    searchable: true
    settings:
      contentTable: '{{%matrixcontent_courses}}'
      maxBlocks: '3'
      minBlocks: ''
      propagationKeyFormat: null
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
