field: 243afeaf-346c-4b8b-af89-9bd633f855e6 # General Awards
fieldLayouts:
  7d9ca38f-51e0-41f1-b511-ce69f8e4d927:
    tabs:
      -
        elements:
          -
            fieldUid: 53352c27-2a47-44a6-a7a3-3d29eaace28e # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7b3e1dd7-7c27-4a5a-839f-8b3f368349ef # Awards
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  7b3e1dd7-7c27-4a5a-839f-8b3f368349ef: # Awards
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: awards
    instructions: ''
    name: Awards
    searchable: true
    settings:
      contentTable: '{{%matrixcontent_awards}}'
      maxBlocks: ''
      minBlocks: ''
      propagationKeyFormat: null
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
  53352c27-2a47-44a6-a7a3-3d29eaace28e: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
