field: 795d3c54-ebb3-4576-b04b-17046dd1da7a # Buttons
fieldLayouts:
  e3f7ea1d-d628-48bf-a7c9-03b7f38505d6:
    tabs:
      -
        fields:
          e433d8bb-8a45-4fc3-b61c-14241393d931: # Button
            required: 0
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  e433d8bb-8a45-4fc3-b61c-14241393d931: # Button
    contentColumnType: string
    fieldGroup: null
    handle: button
    instructions: ''
    name: Button
    searchable: 1
    settings:
      allowCustomText: '1'
      allowTarget: '1'
      defaultText: ''
      selectLinkText: ''
      types:
        presseddigital\linkit\models\Asset:
          customLabel: null
          customSelectionLabel: 'Select an asset'
          enabled: 1
          sources: '*'
        presseddigital\linkit\models\Category:
          customLabel: null
          customSelectionLabel: 'Select a category'
          enabled: 1
          sources: '*'
        presseddigital\linkit\models\Email:
          customLabel: null
          enabled: 1
        presseddigital\linkit\models\Entry:
          customLabel: null
          customSelectionLabel: 'Select an entry'
          enabled: 1
          sources: '*'
        presseddigital\linkit\models\Phone:
          customLabel: null
          enabled: 1
        presseddigital\linkit\models\Url:
          customLabel: null
          enabled: 1
    translationKeyFormat: null
    translationMethod: none
    type: presseddigital\linkit\fields\LinkitField
