field: a33ff164-6e0c-45b9-af83-6ca2cbd9b7cf # CTA
fieldLayouts:
  22f8d8ce-0995-4bec-921b-cc8dff841dab:
    tabs:
      -
        elements:
          -
            fieldUid: dffa5382-9565-4238-b6e2-c72b56a76ddf # Button Text
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b495a4ae-8020-4403-8762-709236a9a0de # Button URL
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: be7f6147-5479-418b-890d-9bb9d155088d # Footer
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  b495a4ae-8020-4403-8762-709236a9a0de: # Button URL
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: buttonUrl
    instructions: ''
    name: 'Button URL'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  be7f6147-5479-418b-890d-9bb9d155088d: # Footer
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: footer
    instructions: 'Extra text underneath button'
    name: Footer
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  dffa5382-9565-4238-b6e2-c72b56a76ddf: # Button Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: ''
    name: 'Button Text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
