field: 0a2670e7-65b0-45b5-96be-318580462d30 # Featured Awards
fieldLayouts:
  2eaefc8d-9076-4f72-88b8-4805b07683a4:
    tabs:
      -
        elements:
          -
            fieldUid: 803dc76f-627a-4c8f-8082-157ada849bea # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 88856313-68a9-44fd-8849-c2e1cecb3695 # Featured Awards
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  803dc76f-627a-4c8f-8082-157ada849bea: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  88856313-68a9-44fd-8849-c2e1cecb3695: # Featured Awards
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: featuredAwards
    instructions: ''
    name: 'Featured Awards'
    searchable: true
    settings:
      contentTable: '{{%matrixcontent_featuredawards}}'
      maxBlocks: ''
      minBlocks: ''
      propagationKeyFormat: null
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
