field: 1e939607-791e-4d0d-9e90-da7db5cb3e58 # Buttons
fieldLayouts:
  df27abbf-a833-41b2-974c-2d7abe0ac338:
    tabs:
      -
        fields:
          7f33d691-0281-4de9-8404-38467e35d592: # Button
            required: 0
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  7f33d691-0281-4de9-8404-38467e35d592: # Button
    contentColumnType: string
    fieldGroup: null
    handle: button
    instructions: ''
    name: Button
    searchable: 1
    settings:
      allowCustomText: '1'
      allowTarget: '1'
      defaultText: ''
      selectLinkText: ''
      types:
        presseddigital\linkit\models\Asset:
          customLabel: null
          customSelectionLabel: 'Select an asset'
          enabled: 1
          sources: '*'
        presseddigital\linkit\models\Category:
          customLabel: null
          customSelectionLabel: 'Select a category'
          enabled: 1
          sources: '*'
        presseddigital\linkit\models\Email:
          customLabel: null
          enabled: 1
        presseddigital\linkit\models\Entry:
          customLabel: null
          customSelectionLabel: 'Select an entry'
          enabled: 1
          sources: '*'
        presseddigital\linkit\models\Phone:
          customLabel: null
          enabled: 1
        presseddigital\linkit\models\Url:
          customLabel: null
          enabled: 1
    translationKeyFormat: null
    translationMethod: none
    type: presseddigital\linkit\fields\LinkitField
