field: ab98011d-e66d-4a2d-a51b-a20e625f4fca # Home Accommodations
fieldLayouts:
  3d120703-3508-4019-b2ab-d1d0f1086f0c:
    tabs:
      -
        elements:
          -
            fieldUid: 6c804630-a47b-490c-8e9f-751844e20691 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 600b7de6-7c7a-4e9b-897f-2f2def2e9bbd # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0b7b3861-eb22-491a-8a7c-85aa93cbf287 # Accommodations
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 48e899c2-d911-461d-90e2-6f404a72376f # Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0b7b3861-eb22-491a-8a7c-85aa93cbf287: # Accommodations
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: accommodations
    instructions: ''
    name: Accommodations
    searchable: true
    settings:
      contentTable: '{{%matrixcontent_accommodations}}'
      maxBlocks: '3'
      minBlocks: ''
      propagationKeyFormat: null
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
  6c804630-a47b-490c-8e9f-751844e20691: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  48e899c2-d911-461d-90e2-6f404a72376f: # Buttons
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: buttons
    instructions: ''
    name: Buttons
    searchable: true
    settings:
      contentTable: '{{%matrixcontent_buttons}}'
      maxBlocks: ''
      minBlocks: ''
      propagationKeyFormat: null
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
  600b7de6-7c7a-4e9b-897f-2f2def2e9bbd: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
