fieldLayouts:
  5546fb56-4478-492d-a256-fbed8f2b4d23:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c61fd93f-7f29-4221-af77-fa7a42f2a104 # Main Navigation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aabae44e-f01d-4963-a719-1cfa9c9430fa
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1c447ce0-d787-4d77-8fd0-ceff01ae4271
        userCondition: null
handle: footer
name: Footer
sortOrder: 2
