fieldLayouts:
  0045a9eb-898f-411c-a248-7ca60da523cf:
    tabs:
      -
        elements:
          -
            fieldUid: c61fd93f-7f29-4221-af77-fa7a42f2a104 # Main Navigation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7df2599b-80fe-4758-8542-add1e40c5d27 # Nav CTA
            instructions: 'Optional - select a special link to be styled as a button next to the main navigation'
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Main Navigation'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: c90430ca-7754-4503-bfdb-eeb26150198b # Secondary Navigation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Secondary Navigation'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 856cdfa4-1efe-4001-886c-d78fedae1bb6 # Announcement
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Announcement
        sortOrder: 3
handle: header
name: Header
sortOrder: 1
