fieldLayouts:
  63f508c4-ad27-404d-b850-2cf10eaa4cf0:
    tabs:
      -
        elements:
          -
            fieldUid: 146613ca-0235-4aee-b159-46c9769d9bc6 # Facebook
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6f49cb67-aebb-4e26-b227-32443ac15a43 # Twitter
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4acc9aa2-b819-474a-a0ef-aefcddc96fba # Instagram
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: socialLinks
name: 'Social Links'
sortOrder: 5
