fieldLayouts:
  63f508c4-ad27-404d-b850-2cf10eaa4cf0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 146613ca-0235-4aee-b159-46c9769d9bc6 # Facebook
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6f3e7732-2319-4d54-9a6d-e4a85f1274e8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6f49cb67-aebb-4e26-b227-32443ac15a43 # Twitter
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c871ac7b-c409-4291-b15e-f8f5c7e7e48d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4acc9aa2-b819-474a-a0ef-aefcddc96fba # Instagram
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 91f45ed2-e65b-4b4a-8001-49f3ae015768
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ac3292f3-6fff-475b-b8d8-8c47a5b31a58
        userCondition: null
handle: socialLinks
name: 'Social Links'
sortOrder: 5
