defaultPlacement: end
enableVersioning: true
handle: accommodationsStructure
name: Accommodations
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  076725fd-bc7e-48fa-88ce-2d58cbee2749: # Arcadia Bluffs (en-US)
    enabledByDefault: true
    hasUrls: true
    template: accommodations/_entry
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 853d2aac-3123-473e-b1bb-738f26767b53
type: structure
