defaultPlacement: end
enableVersioning: true
handle: coursesStructure
name: Courses
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  076725fd-bc7e-48fa-88ce-2d58cbee2749: # Arcadia Bluffs (en-US)
    enabledByDefault: true
    hasUrls: true
    template: courses/_entry
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 62b54826-d286-48d0-bdc5-1608cdfe7392
type: structure
