defaultPlacement: end
enableVersioning: true
handle: diningStructure
name: Dining
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  076725fd-bc7e-48fa-88ce-2d58cbee2749: # Arcadia Bluffs (en-US)
    enabledByDefault: true
    hasUrls: true
    template: dining/_entry
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 3703db49-59bb-491a-99e2-670311a33026
type: structure
