defaultPlacement: end
enableVersioning: true
handle: sunsetCamera
name: 'Sunset Camera'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  076725fd-bc7e-48fa-88ce-2d58cbee2749: # Arcadia Bluffs (en-US)
    enabledByDefault: true
    hasUrls: true
    template: _pages/live-stream
    uriFormat: sunset-camera
type: single
