defaultPlacement: end
enableVersioning: true
handle: utilityPages
name: 'Utility Pages'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  076725fd-bc7e-48fa-88ce-2d58cbee2749: # Arcadia Bluffs (en-US)
    enabledByDefault: true
    hasUrls: true
    template: _pages/subpage
    uriFormat: '{% if object.level == 1 %}{slug}{% else %}{parent.uri}/{slug}{% endif %}'
structure:
  maxLevels: null
  uid: 34f684e4-3b78-42be-b798-fba0bf10089d
type: structure
